// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/vote_on_review/presentation/bloc/vote_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i6;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/entities/vote_on_review.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/repository/vote_on_review_repo.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/down_vote_item_review.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/down_vote_restaurant_review.dart'
    as _i11;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/up_vote_item_review.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/up_vote_restaurant_review.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/vote_on_review_param.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVoteOnReviewRepository_0 extends _i1.SmartFake
    implements _i2.VoteOnReviewRepository {
  _FakeVoteOnReviewRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UpVoteItemReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpVoteItemReviewUseCase extends _i1.Mock
    implements _i4.UpVoteItemReviewUseCase {
  MockUpVoteItemReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_0(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i2.VoteOnReviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>> call(
          _i8.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>);
}

/// A class which mocks [DownVoteItemReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownVoteItemReviewUseCase extends _i1.Mock
    implements _i9.DownVoteItemReviewUseCase {
  MockDownVoteItemReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_0(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i2.VoteOnReviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>> call(
          _i8.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>);
}

/// A class which mocks [UpVoteRestaurantReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpVoteRestaurantReviewUseCase extends _i1.Mock
    implements _i10.UpVoteRestaurantReviewUseCase {
  MockUpVoteRestaurantReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_0(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i2.VoteOnReviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>> call(
          _i8.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>);
}

/// A class which mocks [DownVoteRestaurantReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownVoteRestaurantReviewUseCase extends _i1.Mock
    implements _i11.DownVoteRestaurantReviewUseCase {
  MockDownVoteRestaurantReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_0(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i2.VoteOnReviewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>> call(
          _i8.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.VoteResponse>>);
}
