// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/filter_restaurant/data/repositories/filter_screen_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:rateeat_mobile/src/features/filter_restaurants/data/data_provider/filter_screen_data_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilterDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterDataProvider extends _i1.Mock
    implements _i3.FilterDataProvider {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<String> ratingQuery(
    String? rating,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ratingQuery,
          [
            rating,
            location,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #ratingQuery,
            [
              rating,
              location,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #ratingQuery,
            [
              rating,
              location,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> priceQuery(
    String? price,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #priceQuery,
          [
            price,
            location,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceQuery,
            [
              price,
              location,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceQuery,
            [
              price,
              location,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> priceRangeQuery(
    String? priceRange,
    String? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #priceRangeQuery,
          [
            priceRange,
            location,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceRangeQuery,
            [
              priceRange,
              location,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceRangeQuery,
            [
              priceRange,
              location,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<dynamic>> filterRestaurant(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterRestaurant,
          [query],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
}
