// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/restaurant_detail/data/repositories/restaurant_detail_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/features.dart' as _i2;
import 'package:rateeat_mobile/src/features/restaurant_detail/data/datasources/remote_restaurant_detail_data_provider.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/restaurant_detail/data/models/popular_restaurant_reviews_response_model.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/restaurant_menu/domain/entities/entities.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestaurantModel_0 extends _i1.SmartFake
    implements _i2.RestaurantModel {
  _FakeRestaurantModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePopularRestaurantReviewsResponseModel_1 extends _i1.SmartFake
    implements _i3.PopularRestaurantReviewsResponseModel {
  _FakePopularRestaurantReviewsResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestaurantDetailDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantDetailDataSource extends _i1.Mock
    implements _i4.RestaurantDetailDataSource {
  @override
  _i5.Future<_i2.RestaurantModel> getRestaurantDetail({
    required String? restaurantId,
    double? longitude,
    double? latitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantDetail,
          [],
          {
            #restaurantId: restaurantId,
            #longitude: longitude,
            #latitude: latitude,
          },
        ),
        returnValue:
            _i5.Future<_i2.RestaurantModel>.value(_FakeRestaurantModel_0(
          this,
          Invocation.method(
            #getRestaurantDetail,
            [],
            {
              #restaurantId: restaurantId,
              #longitude: longitude,
              #latitude: latitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.RestaurantModel>.value(_FakeRestaurantModel_0(
          this,
          Invocation.method(
            #getRestaurantDetail,
            [],
            {
              #restaurantId: restaurantId,
              #longitude: longitude,
              #latitude: latitude,
            },
          ),
        )),
      ) as _i5.Future<_i2.RestaurantModel>);

  @override
  _i5.Future<List<_i2.ItemModel>> getRestaurantItems({
    required int? limit,
    required int? page,
    required dynamic restaurantId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantItems,
          [],
          {
            #limit: limit,
            #page: page,
            #restaurantId: restaurantId,
          },
        ),
        returnValue: _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.ItemModel>>.value(<_i2.ItemModel>[]),
      ) as _i5.Future<List<_i2.ItemModel>>);

  @override
  _i5.Future<List<_i6.RestaurantMenuItem>> getPopularItems(
          {required dynamic restaurantId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularItems,
          [],
          {#restaurantId: restaurantId},
        ),
        returnValue: _i5.Future<List<_i6.RestaurantMenuItem>>.value(
            <_i6.RestaurantMenuItem>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.RestaurantMenuItem>>.value(
                <_i6.RestaurantMenuItem>[]),
      ) as _i5.Future<List<_i6.RestaurantMenuItem>>);

  @override
  _i5.Future<_i3.PopularRestaurantReviewsResponseModel>
      getPopularRestaurantReviews({required String? restaurantId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPopularRestaurantReviews,
              [],
              {#restaurantId: restaurantId},
            ),
            returnValue:
                _i5.Future<_i3.PopularRestaurantReviewsResponseModel>.value(
                    _FakePopularRestaurantReviewsResponseModel_1(
              this,
              Invocation.method(
                #getPopularRestaurantReviews,
                [],
                {#restaurantId: restaurantId},
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i3.PopularRestaurantReviewsResponseModel>.value(
                    _FakePopularRestaurantReviewsResponseModel_1(
              this,
              Invocation.method(
                #getPopularRestaurantReviews,
                [],
                {#restaurantId: restaurantId},
              ),
            )),
          ) as _i5.Future<_i3.PopularRestaurantReviewsResponseModel>);
}
