// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/notification/data/repositories/notification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/notification/data/data_sources/notification.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/notification/data/models/notification.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/notification/domain/entities/notification.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationEntity_0 extends _i1.SmartFake
    implements _i2.NotificationEntity {
  _FakeNotificationEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRemoteDataSource extends _i1.Mock
    implements _i3.NotificationsRemoteDataSource {
  @override
  _i4.Future<List<_i5.NotificationModel>> getUserNotifications({
    required String? userId,
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserNotifications,
          [],
          {
            #userId: userId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.NotificationModel>>.value(
            <_i5.NotificationModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.NotificationModel>>.value(
                <_i5.NotificationModel>[]),
      ) as _i4.Future<List<_i5.NotificationModel>>);

  @override
  _i4.Future<_i2.NotificationEntity> markNotificationAsRead(
          {required String? notificationId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsRead,
          [],
          {#notificationId: notificationId},
        ),
        returnValue:
            _i4.Future<_i2.NotificationEntity>.value(_FakeNotificationEntity_0(
          this,
          Invocation.method(
            #markNotificationAsRead,
            [],
            {#notificationId: notificationId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.NotificationEntity>.value(_FakeNotificationEntity_0(
          this,
          Invocation.method(
            #markNotificationAsRead,
            [],
            {#notificationId: notificationId},
          ),
        )),
      ) as _i4.Future<_i2.NotificationEntity>);

  @override
  _i4.Future<int> getUnreadNotificationsCount({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotificationsCount,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
