// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/order_history/domain/usecases/order_detail_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/order_history/data/data.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/order_history/domain/repositories/order_history_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderHistoryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderHistoryRepo extends _i1.Mock implements _i3.OrderHistoryRepo {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.OrderHistoryModel>>> getOrderHistory({
    required String? userId,
    required String? status,
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderHistory,
          [],
          {
            #userId: userId,
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.OrderHistoryModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.OrderHistoryModel>>(
          this,
          Invocation.method(
            #getOrderHistory,
            [],
            {
              #userId: userId,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.OrderHistoryModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.OrderHistoryModel>>(
          this,
          Invocation.method(
            #getOrderHistory,
            [],
            {
              #userId: userId,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.OrderHistoryModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.OrderDetailModel>> getOrderDetail(
          {required String? orderId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderDetail,
          [],
          {#orderId: orderId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.OrderDetailModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.OrderDetailModel>(
          this,
          Invocation.method(
            #getOrderDetail,
            [],
            {#orderId: orderId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.OrderDetailModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.OrderDetailModel>(
          this,
          Invocation.method(
            #getOrderDetail,
            [],
            {#orderId: orderId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.OrderDetailModel>>);
}
