// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/settings/presentation/bloc/user_prefrences/user_prefrence_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/user_profile/domain/domain.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRepository_0 extends _i1.SmartFake
    implements _i2.ProfileRepository {
  _FakeProfileRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UpdateUserPreferenceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserPreferenceUseCase extends _i1.Mock
    implements _i2.UpdateUserPreferenceUseCase {
  @override
  _i2.ProfileRepository get profileRepository => (super.noSuchMethod(
        Invocation.getter(#profileRepository),
        returnValue: _FakeProfileRepository_0(
          this,
          Invocation.getter(#profileRepository),
        ),
        returnValueForMissingStub: _FakeProfileRepository_0(
          this,
          Invocation.getter(#profileRepository),
        ),
      ) as _i2.ProfileRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, dynamic>> call(
          _i2.UpdateUserPreferenceUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, dynamic>>.value(
            _FakeEither_1<_i5.Failure, dynamic>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i5.Failure, dynamic>>.value(
                _FakeEither_1<_i5.Failure, dynamic>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, dynamic>>);
}

/// A class which mocks [GetUserPreferenceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserPreferenceUseCase extends _i1.Mock
    implements _i2.GetUserPreferenceUseCase {
  @override
  _i2.ProfileRepository get profileRepository => (super.noSuchMethod(
        Invocation.getter(#profileRepository),
        returnValue: _FakeProfileRepository_0(
          this,
          Invocation.getter(#profileRepository),
        ),
        returnValueForMissingStub: _FakeProfileRepository_0(
          this,
          Invocation.getter(#profileRepository),
        ),
      ) as _i2.ProfileRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, _i2.UserPreference>> call(
          _i5.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i5.Failure, _i2.UserPreference>>.value(
                _FakeEither_1<_i5.Failure, _i2.UserPreference>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i5.Failure, _i2.UserPreference>>.value(
                _FakeEither_1<_i5.Failure, _i2.UserPreference>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, _i2.UserPreference>>);
}
