// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/live_search/domain/usecases/add_history_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/discover_item/data/models/search_result.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/live_search/data/data_sources/local_search_history_data_source.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/live_search/data/models/history.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/live_search/domain/entities/popular_search_items.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/live_search/domain/repository/live_search_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LiveSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSearchRepository extends _i1.Mock
    implements _i3.LiveSearchRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.PopularSearchItems>> getPopularSearchItems({
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularSearchItems,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PopularSearchItems>>.value(
                _FakeEither_0<_i5.Failure, _i6.PopularSearchItems>(
          this,
          Invocation.method(
            #getPopularSearchItems,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PopularSearchItems>>.value(
                _FakeEither_0<_i5.Failure, _i6.PopularSearchItems>(
          this,
          Invocation.method(
            #getPopularSearchItems,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PopularSearchItems>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i7.RestaurantResult>>> searchRestaurants(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRestaurants,
          [query],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i7.RestaurantResult>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.RestaurantResult>>(
          this,
          Invocation.method(
            #searchRestaurants,
            [query],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i7.RestaurantResult>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.RestaurantResult>>(
          this,
          Invocation.method(
            #searchRestaurants,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.RestaurantResult>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Item>>> searchItems(
    String? query, {
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchItems,
          [query],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Item>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Item>>(
          this,
          Invocation.method(
            #searchItems,
            [query],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.Item>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.Item>>(
          this,
          Invocation.method(
            #searchItems,
            [query],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Item>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addHistory({
    required _i9.History? history,
    _i10.LocalSearchType? localSearchType = _i10.LocalSearchType.restaurants,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHistory,
          [],
          {
            #history: history,
            #localSearchType: localSearchType,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addHistory,
            [],
            {
              #history: history,
              #localSearchType: localSearchType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addHistory,
            [],
            {
              #history: history,
              #localSearchType: localSearchType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.History>>> getHistoryList(
          {_i10.LocalSearchType? localSearchType =
              _i10.LocalSearchType.restaurants}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoryList,
          [],
          {#localSearchType: localSearchType},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i9.History>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.History>>(
          this,
          Invocation.method(
            #getHistoryList,
            [],
            {#localSearchType: localSearchType},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i9.History>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.History>>(
          this,
          Invocation.method(
            #getHistoryList,
            [],
            {#localSearchType: localSearchType},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.History>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearHistory(
          {_i10.LocalSearchType? localSearchType =
              _i10.LocalSearchType.restaurants}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
          {#localSearchType: localSearchType},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #clearHistory,
            [],
            {#localSearchType: localSearchType},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #clearHistory,
            [],
            {#localSearchType: localSearchType},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteHistory({
    required String? id,
    _i10.LocalSearchType? localSearchType = _i10.LocalSearchType.restaurants,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHistory,
          [],
          {
            #id: id,
            #localSearchType: localSearchType,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteHistory,
            [],
            {
              #id: id,
              #localSearchType: localSearchType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteHistory,
            [],
            {
              #id: id,
              #localSearchType: localSearchType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
