// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/order_history/presentation/pages/order_history_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/hive/local_user_model.dart' as _i7;
import 'package:rateeat_mobile/src/features/authentication/data/datasources/local_authentication_datasource.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/order_history/order_history.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/user_profile/user_profile.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchOrderHistoryUseCase_0 extends _i1.SmartFake
    implements _i2.FetchOrderHistoryUseCase {
  _FakeFetchOrderHistoryUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderHistoryState_1 extends _i1.SmartFake
    implements _i2.OrderHistoryState {
  _FakeOrderHistoryState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderHistoryStatusState_2 extends _i1.SmartFake
    implements _i2.OrderHistoryStatusState {
  _FakeOrderHistoryStatusState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderHistoryBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderHistoryBloc extends _i1.Mock implements _i2.OrderHistoryBloc {
  @override
  _i2.FetchOrderHistoryUseCase get fetchOrderHistoryUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#fetchOrderHistoryUseCase),
        returnValue: _FakeFetchOrderHistoryUseCase_0(
          this,
          Invocation.getter(#fetchOrderHistoryUseCase),
        ),
        returnValueForMissingStub: _FakeFetchOrderHistoryUseCase_0(
          this,
          Invocation.getter(#fetchOrderHistoryUseCase),
        ),
      ) as _i2.FetchOrderHistoryUseCase);

  @override
  _i2.OrderHistoryState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrderHistoryState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeOrderHistoryState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.OrderHistoryState);

  @override
  _i3.Stream<_i2.OrderHistoryState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.OrderHistoryState>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.OrderHistoryState>.empty(),
      ) as _i3.Stream<_i2.OrderHistoryState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i2.OrderHistoryEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.OrderHistoryEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.OrderHistoryState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.OrderHistoryEvent>(
    _i4.EventHandler<E, _i2.OrderHistoryState>? handler, {
    _i4.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i4.Transition<_i2.OrderHistoryEvent, _i2.OrderHistoryState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.OrderHistoryEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void onChange(_i4.Change<_i2.OrderHistoryState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OrderHistoryStatusBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderHistoryStatusBloc extends _i1.Mock
    implements _i2.OrderHistoryStatusBloc {
  @override
  _i2.OrderHistoryStatusState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrderHistoryStatusState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeOrderHistoryStatusState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.OrderHistoryStatusState);

  @override
  _i3.Stream<_i2.OrderHistoryStatusState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.OrderHistoryStatusState>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i2.OrderHistoryStatusState>.empty(),
      ) as _i3.Stream<_i2.OrderHistoryStatusState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i2.OrderHistoryStatusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.OrderHistoryStatusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.OrderHistoryStatusState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.OrderHistoryStatusEvent>(
    _i4.EventHandler<E, _i2.OrderHistoryStatusState>? handler, {
    _i4.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i4.Transition<_i2.OrderHistoryStatusEvent,
                  _i2.OrderHistoryStatusState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.OrderHistoryStatusEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void onChange(_i4.Change<_i2.OrderHistoryStatusState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalSource extends _i1.Mock
    implements _i5.AuthenticationLocalSource {
  @override
  _i3.Future<void> cacheUserCredential({required _i6.UserModel? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserCredential,
          [],
          {#user: user},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserCredential(
          {required _i7.LocalUserModel? updatedUserInformation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCredential,
          [],
          {#updatedUserInformation: updatedUserInformation},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearUserCredential() => (super.noSuchMethod(
        Invocation.method(
          #clearUserCredential,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getAppInitialization() => (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
