// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/order_history/presentation/pages/order_history_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter/widgets.dart' as _i8;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:go_router/src/configuration.dart' as _i7;
import 'package:go_router/src/delegate.dart' as _i9;
import 'package:go_router/src/information_provider.dart' as _i10;
import 'package:go_router/src/match.dart' as _i17;
import 'package:go_router/src/parser.dart' as _i11;
import 'package:go_router/src/router.dart' as _i15;
import 'package:go_router/src/state.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:rateeat_mobile/src/features/order/domain/domain.dart' as _i5;
import 'package:rateeat_mobile/src/features/order/presentation/bloc/pay_order/order_bloc.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/order_history/domain/domain.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/order_history/presentation/bloc/order_detail/order_detail_bloc.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/order_history/presentation/bloc/order_history_status/order_history_status_bloc.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetOrderDetailUseCase_0 extends _i1.SmartFake
    implements _i2.GetOrderDetailUseCase {
  _FakeGetOrderDetailUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderDetailState_1 extends _i1.SmartFake
    implements _i3.OrderDetailState {
  _FakeOrderDetailState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderHistoryStatusState_2 extends _i1.SmartFake
    implements _i4.OrderHistoryStatusState {
  _FakeOrderHistoryStatusState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayOrderUseCase_3 extends _i1.SmartFake
    implements _i5.PayOrderUseCase {
  _FakePayOrderUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayOrderState_4 extends _i1.SmartFake implements _i6.PayOrderState {
  _FakePayOrderState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteConfiguration_5 extends _i1.SmartFake
    implements _i7.RouteConfiguration {
  _FakeRouteConfiguration_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackButtonDispatcher_6 extends _i1.SmartFake
    implements _i8.BackButtonDispatcher {
  _FakeBackButtonDispatcher_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoRouterDelegate_7 extends _i1.SmartFake
    implements _i9.GoRouterDelegate {
  _FakeGoRouterDelegate_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoRouteInformationProvider_8 extends _i1.SmartFake
    implements _i10.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoRouteInformationParser_9 extends _i1.SmartFake
    implements _i11.GoRouteInformationParser {
  _FakeGoRouteInformationParser_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoRouterState_10 extends _i1.SmartFake
    implements _i12.GoRouterState {
  _FakeGoRouterState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDetailBloc extends _i1.Mock implements _i3.OrderDetailBloc {
  @override
  _i2.GetOrderDetailUseCase get orderUseCase => (super.noSuchMethod(
        Invocation.getter(#orderUseCase),
        returnValue: _FakeGetOrderDetailUseCase_0(
          this,
          Invocation.getter(#orderUseCase),
        ),
        returnValueForMissingStub: _FakeGetOrderDetailUseCase_0(
          this,
          Invocation.getter(#orderUseCase),
        ),
      ) as _i2.GetOrderDetailUseCase);

  @override
  _i3.OrderDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrderDetailState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeOrderDetailState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.OrderDetailState);

  @override
  _i13.Stream<_i3.OrderDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i3.OrderDetailState>.empty(),
        returnValueForMissingStub: _i13.Stream<_i3.OrderDetailState>.empty(),
      ) as _i13.Stream<_i3.OrderDetailState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i3.OrderDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i3.OrderDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.OrderDetailState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i3.OrderDetailEvent>(
    _i14.EventHandler<E, _i3.OrderDetailState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i3.OrderDetailEvent, _i3.OrderDetailState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i3.OrderDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i14.Change<_i3.OrderDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OrderHistoryStatusBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderHistoryStatusBloc extends _i1.Mock
    implements _i4.OrderHistoryStatusBloc {
  @override
  _i4.OrderHistoryStatusState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrderHistoryStatusState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeOrderHistoryStatusState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.OrderHistoryStatusState);

  @override
  _i13.Stream<_i4.OrderHistoryStatusState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i4.OrderHistoryStatusState>.empty(),
        returnValueForMissingStub:
            _i13.Stream<_i4.OrderHistoryStatusState>.empty(),
      ) as _i13.Stream<_i4.OrderHistoryStatusState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i4.OrderHistoryStatusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i4.OrderHistoryStatusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.OrderHistoryStatusState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i4.OrderHistoryStatusEvent>(
    _i14.EventHandler<E, _i4.OrderHistoryStatusState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i4.OrderHistoryStatusEvent,
                  _i4.OrderHistoryStatusState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i4.OrderHistoryStatusEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i14.Change<_i4.OrderHistoryStatusState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PayOrderBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayOrderBloc extends _i1.Mock implements _i6.PayOrderBloc {
  @override
  _i5.PayOrderUseCase get payOrderUseCase => (super.noSuchMethod(
        Invocation.getter(#payOrderUseCase),
        returnValue: _FakePayOrderUseCase_3(
          this,
          Invocation.getter(#payOrderUseCase),
        ),
        returnValueForMissingStub: _FakePayOrderUseCase_3(
          this,
          Invocation.getter(#payOrderUseCase),
        ),
      ) as _i5.PayOrderUseCase);

  @override
  _i6.PayOrderState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePayOrderState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePayOrderState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.PayOrderState);

  @override
  _i13.Stream<_i6.PayOrderState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i6.PayOrderState>.empty(),
        returnValueForMissingStub: _i13.Stream<_i6.PayOrderState>.empty(),
      ) as _i13.Stream<_i6.PayOrderState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i6.PayOrderEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.PayOrderEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.PayOrderState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.PayOrderEvent>(
    _i14.EventHandler<E, _i6.PayOrderState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i6.PayOrderEvent, _i6.PayOrderState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i6.PayOrderEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i14.Change<_i6.PayOrderState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i15.GoRouter {
  @override
  _i7.RouteConfiguration get configuration => (super.noSuchMethod(
        Invocation.getter(#configuration),
        returnValue: _FakeRouteConfiguration_5(
          this,
          Invocation.getter(#configuration),
        ),
        returnValueForMissingStub: _FakeRouteConfiguration_5(
          this,
          Invocation.getter(#configuration),
        ),
      ) as _i7.RouteConfiguration);

  @override
  set configuration(_i7.RouteConfiguration? _configuration) =>
      super.noSuchMethod(
        Invocation.setter(
          #configuration,
          _configuration,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.BackButtonDispatcher get backButtonDispatcher => (super.noSuchMethod(
        Invocation.getter(#backButtonDispatcher),
        returnValue: _FakeBackButtonDispatcher_6(
          this,
          Invocation.getter(#backButtonDispatcher),
        ),
        returnValueForMissingStub: _FakeBackButtonDispatcher_6(
          this,
          Invocation.getter(#backButtonDispatcher),
        ),
      ) as _i8.BackButtonDispatcher);

  @override
  _i9.GoRouterDelegate get routerDelegate => (super.noSuchMethod(
        Invocation.getter(#routerDelegate),
        returnValue: _FakeGoRouterDelegate_7(
          this,
          Invocation.getter(#routerDelegate),
        ),
        returnValueForMissingStub: _FakeGoRouterDelegate_7(
          this,
          Invocation.getter(#routerDelegate),
        ),
      ) as _i9.GoRouterDelegate);

  @override
  set routerDelegate(_i9.GoRouterDelegate? _routerDelegate) =>
      super.noSuchMethod(
        Invocation.setter(
          #routerDelegate,
          _routerDelegate,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
        Invocation.getter(#routeInformationProvider),
        returnValue: _FakeGoRouteInformationProvider_8(
          this,
          Invocation.getter(#routeInformationProvider),
        ),
        returnValueForMissingStub: _FakeGoRouteInformationProvider_8(
          this,
          Invocation.getter(#routeInformationProvider),
        ),
      ) as _i10.GoRouteInformationProvider);

  @override
  set routeInformationProvider(
          _i10.GoRouteInformationProvider? _routeInformationProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #routeInformationProvider,
          _routeInformationProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
        Invocation.getter(#routeInformationParser),
        returnValue: _FakeGoRouteInformationParser_9(
          this,
          Invocation.getter(#routeInformationParser),
        ),
        returnValueForMissingStub: _FakeGoRouteInformationParser_9(
          this,
          Invocation.getter(#routeInformationParser),
        ),
      ) as _i11.GoRouteInformationParser);

  @override
  set routeInformationParser(
          _i11.GoRouteInformationParser? _routeInformationParser) =>
      super.noSuchMethod(
        Invocation.setter(
          #routeInformationParser,
          _routeInformationParser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get overridePlatformDefaultLocation => (super.noSuchMethod(
        Invocation.getter(#overridePlatformDefaultLocation),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.GoRouterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGoRouterState_10(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeGoRouterState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i12.GoRouterState);

  @override
  bool canPop() => (super.noSuchMethod(
        Invocation.method(
          #canPop,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedLocation,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #fragment: fragment,
          },
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #namedLocation,
            [name],
            {
              #pathParameters: pathParameters,
              #queryParameters: queryParameters,
              #fragment: fragment,
            },
          ),
        ),
        returnValueForMissingStub: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #namedLocation,
            [name],
            {
              #pathParameters: pathParameters,
              #queryParameters: queryParameters,
              #fragment: fragment,
            },
          ),
        ),
      ) as String);

  @override
  void go(
    String? location, {
    Object? extra,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #go,
          [location],
          {#extra: extra},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void restore(_i17.RouteMatchList? matchList) => super.noSuchMethod(
        Invocation.method(
          #restore,
          [matchList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #goNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
            #fragment: fragment,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?> push<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [location],
          {#extra: extra},
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [location],
          {#extra: extra},
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushReplacementNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  _i13.Future<T?> replace<T>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [location],
          {#extra: extra},
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  _i13.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i13.Future<T?>.value(),
        returnValueForMissingStub: _i13.Future<T?>.value(),
      ) as _i13.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
