// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/restaurant_menu/domain/usecases/add_candidate_item_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/homepage/data/models/models.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/restaurant_menu/domain/entities/menu.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/restaurant_menu/domain/entities/restaurant_category.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/restaurant_menu/domain/repositories/restaurant_menu_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestaurantMenuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantMenuRepository extends _i1.Mock
    implements _i3.RestaurantMenuRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemModel>>>
      getRestaurantMenuItems({
    required String? restaurantId,
    required int? limit,
    required int? page,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRestaurantMenuItems,
              [],
              {
                #restaurantId: restaurantId,
                #limit: limit,
                #page: page,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemModel>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.ItemModel>>(
              this,
              Invocation.method(
                #getRestaurantMenuItems,
                [],
                {
                  #restaurantId: restaurantId,
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemModel>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.ItemModel>>(
              this,
              Invocation.method(
                #getRestaurantMenuItems,
                [],
                {
                  #restaurantId: restaurantId,
                  #limit: limit,
                  #page: page,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Menu>> getRestaurantMenuCategoryItems({
    required String? restaurantId,
    required String? categoryName,
    required int? page,
    required int? limit,
    required String? query,
    required String? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantMenuCategoryItems,
          [],
          {
            #restaurantId: restaurantId,
            #categoryName: categoryName,
            #page: page,
            #limit: limit,
            #query: query,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Menu>>.value(
            _FakeEither_0<_i5.Failure, _i7.Menu>(
          this,
          Invocation.method(
            #getRestaurantMenuCategoryItems,
            [],
            {
              #restaurantId: restaurantId,
              #categoryName: categoryName,
              #page: page,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i7.Menu>>.value(
                _FakeEither_0<_i5.Failure, _i7.Menu>(
          this,
          Invocation.method(
            #getRestaurantMenuCategoryItems,
            [],
            {
              #restaurantId: restaurantId,
              #categoryName: categoryName,
              #page: page,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Menu>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Item>> addCandidateItem({
    required String? itemName,
    required String? price,
    required List<_i9.File>? itemImages,
    required String? menuId,
    required String? categoryName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCandidateItem,
          [],
          {
            #itemName: itemName,
            #price: price,
            #itemImages: itemImages,
            #menuId: menuId,
            #categoryName: categoryName,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Item>>.value(
            _FakeEither_0<_i5.Failure, _i8.Item>(
          this,
          Invocation.method(
            #addCandidateItem,
            [],
            {
              #itemName: itemName,
              #price: price,
              #itemImages: itemImages,
              #menuId: menuId,
              #categoryName: categoryName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i8.Item>>.value(
                _FakeEither_0<_i5.Failure, _i8.Item>(
          this,
          Invocation.method(
            #addCandidateItem,
            [],
            {
              #itemName: itemName,
              #price: price,
              #itemImages: itemImages,
              #menuId: menuId,
              #categoryName: categoryName,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.Item>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.RestaurantCategory>>>
      getRestaurantMenuCategories({required String? restaurantId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRestaurantMenuCategories,
              [],
              {#restaurantId: restaurantId},
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.RestaurantCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.RestaurantCategory>>(
              this,
              Invocation.method(
                #getRestaurantMenuCategories,
                [],
                {#restaurantId: restaurantId},
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.RestaurantCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.RestaurantCategory>>(
              this,
              Invocation.method(
                #getRestaurantMenuCategories,
                [],
                {#restaurantId: restaurantId},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.RestaurantCategory>>>);
}
