// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/vote_on_review/domain/usecases/vote_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/entities/vote_on_review.dart'
    as _i6;

import 'vote_usecase_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockVoteOnReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockVoteOnReviewRepository extends _i1.Mock
    implements _i3.MockVoteOnReviewRepository {
  MockMockVoteOnReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>> upVoteItemReview({
    required String? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upVoteItemReview,
          [],
          {
            #reviewId: reviewId,
            #userId: userId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.VoteResponse>(
          this,
          Invocation.method(
            #upVoteItemReview,
            [],
            {
              #reviewId: reviewId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>> downVoteItemReview({
    required String? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downVoteItemReview,
          [],
          {
            #reviewId: reviewId,
            #userId: userId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.VoteResponse>(
          this,
          Invocation.method(
            #downVoteItemReview,
            [],
            {
              #reviewId: reviewId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>> upVoteRestaurantReview({
    required String? reviewId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upVoteRestaurantReview,
          [],
          {
            #reviewId: reviewId,
            #userId: userId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.VoteResponse>(
          this,
          Invocation.method(
            #upVoteRestaurantReview,
            [],
            {
              #reviewId: reviewId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>
      downVoteRestaurantReview({
    required String? reviewId,
    required String? userId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #downVoteRestaurantReview,
              [],
              {
                #reviewId: reviewId,
                #userId: userId,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>.value(
                    _FakeEither_0<_i5.Failure, _i6.VoteResponse>(
              this,
              Invocation.method(
                #downVoteRestaurantReview,
                [],
                {
                  #reviewId: reviewId,
                  #userId: userId,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.VoteResponse>>);
}
