// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/leaderboard/domain/usecase/weekly_leader_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/error/failure.dart' as _i5;
import 'package:rateeat_mobile/src/features/leaderboard/data/model/leadermodel.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/leaderboard/data/model/monthly_leader_board_request_model.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/leaderboard/data/model/weekly_leader_board_request_model.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/leaderboard/domain/entities/monthly_leader_board_responses.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/leaderboard/domain/entities/weekly_leader_board_responses.dart'
    as _i7;

import 'weekly_leader_usecase_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockLeaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockLeaderRepository extends _i1.Mock
    implements _i3.MockLeaderRepository {
  MockMockLeaderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.LeaderBoardModel>>>
      getLeaderBoard({
    required int? page,
    required int? limit,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getLeaderBoard,
              [],
              {
                #page: page,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.LeaderBoardModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.LeaderBoardModel>>(
              this,
              Invocation.method(
                #getLeaderBoard,
                [],
                {
                  #page: page,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.LeaderBoardModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WeeklyLeaderBoardResponses>>
      getWeeklyLeaderBoard(
              {required _i8.WeeklyLeaderBoardRequestModel?
                  weeklyLeaderBoardRequestModel}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWeeklyLeaderBoard,
              [],
              {#weeklyLeaderBoardRequestModel: weeklyLeaderBoardRequestModel},
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, _i7.WeeklyLeaderBoardResponses>>.value(
                _FakeEither_0<_i5.Failure, _i7.WeeklyLeaderBoardResponses>(
              this,
              Invocation.method(
                #getWeeklyLeaderBoard,
                [],
                {#weeklyLeaderBoardRequestModel: weeklyLeaderBoardRequestModel},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i7.WeeklyLeaderBoardResponses>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.MonthlyLeaderBoardResponses>>
      getMonthlyLeaderBoard(
              {required _i10.MonthlyLeaderBoardRequestModel?
                  monthlyLeaderBoardRequestModel}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getMonthlyLeaderBoard,
              [],
              {#monthlyLeaderBoardRequestModel: monthlyLeaderBoardRequestModel},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i9.MonthlyLeaderBoardResponses>>.value(
                _FakeEither_0<_i5.Failure, _i9.MonthlyLeaderBoardResponses>(
              this,
              Invocation.method(
                #getMonthlyLeaderBoard,
                [],
                {
                  #monthlyLeaderBoardRequestModel:
                      monthlyLeaderBoardRequestModel
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i9.MonthlyLeaderBoardResponses>>);
}
