// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/live_search/data/repositories/live_search_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/discover_item/data/models/search_result.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/features.dart' as _i5;
import 'package:rateeat_mobile/src/features/live_search/data/data_sources/live_search_data_provider.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/live_search/data/data_sources/local_search_history_data_source.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/live_search/data/models/history.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LiveSearchDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSearchDataProvider extends _i1.Mock
    implements _i2.LiveSearchDataProvider {
  @override
  _i3.Future<List<_i4.RestaurantResult>> searchRestaurants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRestaurants,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.RestaurantResult>>.value(
            <_i4.RestaurantResult>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.RestaurantResult>>.value(
            <_i4.RestaurantResult>[]),
      ) as _i3.Future<List<_i4.RestaurantResult>>);

  @override
  _i3.Future<List<_i5.ItemModel>> searchItems(
    String? query, {
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchItems,
          [query],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i3.Future<List<_i5.ItemModel>>.value(<_i5.ItemModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.ItemModel>>.value(<_i5.ItemModel>[]),
      ) as _i3.Future<List<_i5.ItemModel>>);

  @override
  _i3.Future<List<_i5.RestaurantModel>> getPopularRestaurants({
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularRestaurants,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue: _i3.Future<List<_i5.RestaurantModel>>.value(
            <_i5.RestaurantModel>[]),
        returnValueForMissingStub: _i3.Future<List<_i5.RestaurantModel>>.value(
            <_i5.RestaurantModel>[]),
      ) as _i3.Future<List<_i5.RestaurantModel>>);

  @override
  _i3.Future<List<_i5.ItemModel>> getPopularItems({
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularItems,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue: _i3.Future<List<_i5.ItemModel>>.value(<_i5.ItemModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.ItemModel>>.value(<_i5.ItemModel>[]),
      ) as _i3.Future<List<_i5.ItemModel>>);
}

/// A class which mocks [LocalSearchHistoryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalSearchHistoryDataSource extends _i1.Mock
    implements _i6.LocalSearchHistoryDataSource {
  @override
  _i3.Future<void> addHistory({
    required _i7.History? history,
    _i6.LocalSearchType? localSearchType = _i6.LocalSearchType.restaurants,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHistory,
          [],
          {
            #history: history,
            #localSearchType: localSearchType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.History>> getHistoryList(
          {_i6.LocalSearchType? localSearchType =
              _i6.LocalSearchType.restaurants}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoryList,
          [],
          {#localSearchType: localSearchType},
        ),
        returnValue: _i3.Future<List<_i7.History>>.value(<_i7.History>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.History>>.value(<_i7.History>[]),
      ) as _i3.Future<List<_i7.History>>);

  @override
  _i3.Future<void> clearHistory(
          {_i6.LocalSearchType? localSearchType =
              _i6.LocalSearchType.restaurants}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
          {#localSearchType: localSearchType},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHistory({
    required String? id,
    _i6.LocalSearchType? localSearchType = _i6.LocalSearchType.restaurants,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHistory,
          [],
          {
            #id: id,
            #localSearchType: localSearchType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
