// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/item_detail/presentation/pages/item_detail_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:ui' as _i37;

import 'package:dartz/dartz.dart' as _i18;
import 'package:firebase_analytics/firebase_analytics.dart' as _i4;
import 'package:flutter/material.dart' as _i27;
import 'package:flutter_bloc/flutter_bloc.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i34;
import 'package:rateeat_mobile/src/core/core.dart' as _i41;
import 'package:rateeat_mobile/src/core/hive/local_user_model.dart' as _i25;
import 'package:rateeat_mobile/src/core/hive/user_engagement_analytics.dart'
    as _i28;
import 'package:rateeat_mobile/src/core/service/firebase_analytics.dart'
    as _i29;
import 'package:rateeat_mobile/src/core/service/local_analytics.dart' as _i26;
import 'package:rateeat_mobile/src/features/add_to_favorite/domain/use_cases/use_cases.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/add_to_favorite/presentation/bloc/favorite_bloc.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/authentication/data/datasources/local_authentication_datasource.dart'
    as _i23;
import 'package:rateeat_mobile/src/features/item_detail/domain/domain.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/item_detail/item_detail.dart'
    as _i19;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/item_detail/item_detail_event.dart'
    as _i21;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/item_detail/item_detail_state.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/popular_item_reviews/popular_item_reviews_bloc.dart'
    as _i30;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/popular_item_reviews/popular_item_reviews_event.dart'
    as _i31;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/popular_item_reviews/popular_item_reviews_state.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/recommended_items/recommended_items.dart'
    as _i32;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/recommended_items/recommended_items_event.dart'
    as _i33;
import 'package:rateeat_mobile/src/features/item_detail/presentation/bloc/recommended_items/recommended_items_state.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/review/domain/use_cases/delete_item_review_usecase.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/review/presentation/bloc/delete_item_review/delete_item_review_bloc.dart'
    as _i11;
import 'package:rateeat_mobile/src/features/user_profile/presentation/pages/custom_tab_bar.dart'
    as _i38;
import 'package:rateeat_mobile/src/features/user_profile/user_profile.dart'
    as _i24;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/entities/vote_on_review.dart'
    as _i42;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/repository/vote_on_review_repo.dart'
    as _i17;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/down_vote_item_review.dart'
    as _i13;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/down_vote_restaurant_review.dart'
    as _i15;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/up_vote_item_review.dart'
    as _i12;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/up_vote_restaurant_review.dart'
    as _i14;
import 'package:rateeat_mobile/src/features/vote_on_review/domain/use_cases/vote_on_review_param.dart'
    as _i43;
import 'package:rateeat_mobile/src/features/vote_on_review/presentation/bloc/vote_on_review_bloc.dart'
    as _i39;
import 'package:rateeat_mobile/src/features/vote_on_review/presentation/bloc/vote_on_review_event.dart'
    as _i40;
import 'package:rateeat_mobile/src/features/vote_on_review/presentation/bloc/vote_on_review_state.dart'
    as _i16;
import 'package:video_player/src/closed_caption_file.dart' as _i36;
import 'package:video_player/video_player.dart' as _i9;
import 'package:video_player_platform_interface/video_player_platform_interface.dart'
    as _i35;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetItemUseCase_0 extends _i1.SmartFake
    implements _i2.GetItemUseCase {
  _FakeGetItemUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItemDetailState_1 extends _i1.SmartFake
    implements _i3.ItemDetailState {
  _FakeItemDetailState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalyticsObserver_2 extends _i1.SmartFake
    implements _i4.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularItemReviewsUseCase_3 extends _i1.SmartFake
    implements _i2.GetPopularItemReviewsUseCase {
  _FakeGetPopularItemReviewsUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePopularItemReviewsState_4 extends _i1.SmartFake
    implements _i5.PopularItemReviewsState {
  _FakePopularItemReviewsState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetItemRecommendationsUseCase_5 extends _i1.SmartFake
    implements _i2.GetItemRecommendationsUseCase {
  _FakeGetItemRecommendationsUseCase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailRecommendedState_6 extends _i1.SmartFake
    implements _i6.DetailRecommendedState {
  _FakeDetailRecommendedState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddItemToFavoriteUseCase_7 extends _i1.SmartFake
    implements _i7.AddItemToFavoriteUseCase {
  _FakeAddItemToFavoriteUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveItemFromFavoriteUseCase_8 extends _i1.SmartFake
    implements _i7.RemoveItemFromFavoriteUseCase {
  _FakeRemoveItemFromFavoriteUseCase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddRestaurantToFavoriteUseCase_9 extends _i1.SmartFake
    implements _i7.AddRestaurantToFavoriteUseCase {
  _FakeAddRestaurantToFavoriteUseCase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveRestaurantFromFavoriteUseCase_10 extends _i1.SmartFake
    implements _i7.RemoveRestaurantFromFavoriteUseCase {
  _FakeRemoveRestaurantFromFavoriteUseCase_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFavoriteState_11 extends _i1.SmartFake implements _i8.FavoriteState {
  _FakeFavoriteState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoPlayerValue_12 extends _i1.SmartFake
    implements _i9.VideoPlayerValue {
  _FakeVideoPlayerValue_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteItemReviewUseCase_13 extends _i1.SmartFake
    implements _i10.DeleteItemReviewUseCase {
  _FakeDeleteItemReviewUseCase_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteItemReviewState_14 extends _i1.SmartFake
    implements _i11.DeleteItemReviewState {
  _FakeDeleteItemReviewState_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpVoteItemReviewUseCase_15 extends _i1.SmartFake
    implements _i12.UpVoteItemReviewUseCase {
  _FakeUpVoteItemReviewUseCase_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownVoteItemReviewUseCase_16 extends _i1.SmartFake
    implements _i13.DownVoteItemReviewUseCase {
  _FakeDownVoteItemReviewUseCase_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpVoteRestaurantReviewUseCase_17 extends _i1.SmartFake
    implements _i14.UpVoteRestaurantReviewUseCase {
  _FakeUpVoteRestaurantReviewUseCase_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownVoteRestaurantReviewUseCase_18 extends _i1.SmartFake
    implements _i15.DownVoteRestaurantReviewUseCase {
  _FakeDownVoteRestaurantReviewUseCase_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoteOnReviewState_19 extends _i1.SmartFake
    implements _i16.VoteOnReviewState {
  _FakeVoteOnReviewState_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoteOnReviewRepository_20 extends _i1.SmartFake
    implements _i17.VoteOnReviewRepository {
  _FakeVoteOnReviewRepository_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_21<L, R> extends _i1.SmartFake implements _i18.Either<L, R> {
  _FakeEither_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ItemDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemDetailBloc extends _i1.Mock implements _i19.ItemDetailBloc {
  @override
  _i2.GetItemUseCase get itemUseCase => (super.noSuchMethod(
        Invocation.getter(#itemUseCase),
        returnValue: _FakeGetItemUseCase_0(
          this,
          Invocation.getter(#itemUseCase),
        ),
        returnValueForMissingStub: _FakeGetItemUseCase_0(
          this,
          Invocation.getter(#itemUseCase),
        ),
      ) as _i2.GetItemUseCase);

  @override
  _i3.ItemDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeItemDetailState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeItemDetailState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.ItemDetailState);

  @override
  _i20.Stream<_i3.ItemDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i3.ItemDetailState>.empty(),
        returnValueForMissingStub: _i20.Stream<_i3.ItemDetailState>.empty(),
      ) as _i20.Stream<_i3.ItemDetailState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i21.ItemDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i21.ItemDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.ItemDetailState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i21.ItemDetailEvent>(
    _i22.EventHandler<E, _i3.ItemDetailState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i21.ItemDetailEvent, _i3.ItemDetailState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i21.ItemDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i3.ItemDetailState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalSource extends _i1.Mock
    implements _i23.AuthenticationLocalSource {
  @override
  _i20.Future<void> cacheUserCredential({required _i24.UserModel? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserCredential,
          [],
          {#user: user},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateUserCredential(
          {required _i25.LocalUserModel? updatedUserInformation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCredential,
          [],
          {#updatedUserInformation: updatedUserInformation},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> clearUserCredential() => (super.noSuchMethod(
        Invocation.method(
          #clearUserCredential,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<bool> getAppInitialization() => (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
        returnValueForMissingStub: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);
}

/// A class which mocks [LocalAnalyticsObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAnalyticsObserver extends _i1.Mock
    implements _i26.LocalAnalyticsObserver {
  @override
  void didPush(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> clearSessionAnalyticsData() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionAnalyticsData,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateUserEngagementAnalytics(
          {required _i28.UserEngagementAnalytics? update}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserEngagementAnalytics,
          [],
          {#update: update},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateItemAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateRestaurantAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateRestaurantSearchAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantSearchAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateItemSearchAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemSearchAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateRestaurantShareAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantShareAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateItemShareAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemShareAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void didPop(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i27.Route<dynamic>? newRoute,
    _i27.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i27.Route<dynamic>? topRoute,
    _i27.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AnalyticsObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsObserver extends _i1.Mock implements _i29.AnalyticsObserver {
  @override
  _i4.FirebaseAnalyticsObserver getAnalyticsObserver() => (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsObserver,
          [],
        ),
        returnValue: _FakeFirebaseAnalyticsObserver_2(
          this,
          Invocation.method(
            #getAnalyticsObserver,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFirebaseAnalyticsObserver_2(
          this,
          Invocation.method(
            #getAnalyticsObserver,
            [],
          ),
        ),
      ) as _i4.FirebaseAnalyticsObserver);

  @override
  void didPush(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> logLogin({
    required String? method,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logLogin,
          [],
          {
            #method: method,
            #params: params,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> logSignUp({
    required String? method,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSignUp,
          [],
          {
            #method: method,
            #params: params,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> sendAnalyticsEvent({
    required String? eventName,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAnalyticsEvent,
          [],
          {
            #eventName: eventName,
            #params: params,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setUserId({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [],
          {#userId: userId},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [],
          {
            #name: name,
            #value: value,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setAnalyticsCollectionEnabled() => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsCollectionEnabled,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setAppInstanceId() => (super.noSuchMethod(
        Invocation.method(
          #setAppInstanceId,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> resetAnalyticsData() => (super.noSuchMethod(
        Invocation.method(
          #resetAnalyticsData,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void didPop(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i27.Route<dynamic>? newRoute,
    _i27.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i27.Route<dynamic>? topRoute,
    _i27.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i27.Route<dynamic>? route,
    _i27.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PopularItemReviewsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularItemReviewsBloc extends _i1.Mock
    implements _i30.PopularItemReviewsBloc {
  @override
  _i2.GetPopularItemReviewsUseCase get getPopularItemReviewsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getPopularItemReviewsUseCase),
        returnValue: _FakeGetPopularItemReviewsUseCase_3(
          this,
          Invocation.getter(#getPopularItemReviewsUseCase),
        ),
        returnValueForMissingStub: _FakeGetPopularItemReviewsUseCase_3(
          this,
          Invocation.getter(#getPopularItemReviewsUseCase),
        ),
      ) as _i2.GetPopularItemReviewsUseCase);

  @override
  _i5.PopularItemReviewsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePopularItemReviewsState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePopularItemReviewsState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.PopularItemReviewsState);

  @override
  _i20.Stream<_i5.PopularItemReviewsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i5.PopularItemReviewsState>.empty(),
        returnValueForMissingStub:
            _i20.Stream<_i5.PopularItemReviewsState>.empty(),
      ) as _i20.Stream<_i5.PopularItemReviewsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i31.PopularItemReviewsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i31.PopularItemReviewsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.PopularItemReviewsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i31.PopularItemReviewsEvent>(
    _i22.EventHandler<E, _i5.PopularItemReviewsState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i31.PopularItemReviewsEvent,
                  _i5.PopularItemReviewsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i31.PopularItemReviewsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i5.PopularItemReviewsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DetailRecommendationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailRecommendationBloc extends _i1.Mock
    implements _i32.DetailRecommendationBloc {
  @override
  _i2.GetItemRecommendationsUseCase get getItemRecommendationsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getItemRecommendationsUseCase),
        returnValue: _FakeGetItemRecommendationsUseCase_5(
          this,
          Invocation.getter(#getItemRecommendationsUseCase),
        ),
        returnValueForMissingStub: _FakeGetItemRecommendationsUseCase_5(
          this,
          Invocation.getter(#getItemRecommendationsUseCase),
        ),
      ) as _i2.GetItemRecommendationsUseCase);

  @override
  _i6.DetailRecommendedState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDetailRecommendedState_6(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDetailRecommendedState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.DetailRecommendedState);

  @override
  _i20.Stream<_i6.DetailRecommendedState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i6.DetailRecommendedState>.empty(),
        returnValueForMissingStub:
            _i20.Stream<_i6.DetailRecommendedState>.empty(),
      ) as _i20.Stream<_i6.DetailRecommendedState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i33.RecommendedItemsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i33.RecommendedItemsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.DetailRecommendedState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i33.RecommendedItemsEvent>(
    _i22.EventHandler<E, _i6.DetailRecommendedState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i33.RecommendedItemsEvent,
                  _i6.DetailRecommendedState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i33.RecommendedItemsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i6.DetailRecommendedState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoriteBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteBloc extends _i1.Mock implements _i8.FavoriteBloc {
  @override
  _i7.AddItemToFavoriteUseCase get addToFavorite => (super.noSuchMethod(
        Invocation.getter(#addToFavorite),
        returnValue: _FakeAddItemToFavoriteUseCase_7(
          this,
          Invocation.getter(#addToFavorite),
        ),
        returnValueForMissingStub: _FakeAddItemToFavoriteUseCase_7(
          this,
          Invocation.getter(#addToFavorite),
        ),
      ) as _i7.AddItemToFavoriteUseCase);

  @override
  _i7.RemoveItemFromFavoriteUseCase get removeFromFavorite =>
      (super.noSuchMethod(
        Invocation.getter(#removeFromFavorite),
        returnValue: _FakeRemoveItemFromFavoriteUseCase_8(
          this,
          Invocation.getter(#removeFromFavorite),
        ),
        returnValueForMissingStub: _FakeRemoveItemFromFavoriteUseCase_8(
          this,
          Invocation.getter(#removeFromFavorite),
        ),
      ) as _i7.RemoveItemFromFavoriteUseCase);

  @override
  _i7.AddRestaurantToFavoriteUseCase get addRestaurantToFavorite =>
      (super.noSuchMethod(
        Invocation.getter(#addRestaurantToFavorite),
        returnValue: _FakeAddRestaurantToFavoriteUseCase_9(
          this,
          Invocation.getter(#addRestaurantToFavorite),
        ),
        returnValueForMissingStub: _FakeAddRestaurantToFavoriteUseCase_9(
          this,
          Invocation.getter(#addRestaurantToFavorite),
        ),
      ) as _i7.AddRestaurantToFavoriteUseCase);

  @override
  _i7.RemoveRestaurantFromFavoriteUseCase get removeRestaurantFromFavorite =>
      (super.noSuchMethod(
        Invocation.getter(#removeRestaurantFromFavorite),
        returnValue: _FakeRemoveRestaurantFromFavoriteUseCase_10(
          this,
          Invocation.getter(#removeRestaurantFromFavorite),
        ),
        returnValueForMissingStub: _FakeRemoveRestaurantFromFavoriteUseCase_10(
          this,
          Invocation.getter(#removeRestaurantFromFavorite),
        ),
      ) as _i7.RemoveRestaurantFromFavoriteUseCase);

  @override
  _i8.FavoriteState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFavoriteState_11(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeFavoriteState_11(
          this,
          Invocation.getter(#state),
        ),
      ) as _i8.FavoriteState);

  @override
  _i20.Stream<_i8.FavoriteState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i8.FavoriteState>.empty(),
        returnValueForMissingStub: _i20.Stream<_i8.FavoriteState>.empty(),
      ) as _i20.Stream<_i8.FavoriteState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i8.FavoriteEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i8.FavoriteEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i8.FavoriteState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i8.FavoriteEvent>(
    _i22.EventHandler<E, _i8.FavoriteState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i8.FavoriteEvent, _i8.FavoriteState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i8.FavoriteEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i8.FavoriteState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VideoPlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerController extends _i1.Mock
    implements _i9.VideoPlayerController {
  @override
  String get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _i34.dummyValue<String>(
          this,
          Invocation.getter(#dataSource),
        ),
        returnValueForMissingStub: _i34.dummyValue<String>(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as String);

  @override
  Map<String, String> get httpHeaders => (super.noSuchMethod(
        Invocation.getter(#httpHeaders),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  _i35.DataSourceType get dataSourceType => (super.noSuchMethod(
        Invocation.getter(#dataSourceType),
        returnValue: _i35.DataSourceType.asset,
        returnValueForMissingStub: _i35.DataSourceType.asset,
      ) as _i35.DataSourceType);

  @override
  _i35.VideoViewType get viewType => (super.noSuchMethod(
        Invocation.getter(#viewType),
        returnValue: _i35.VideoViewType.textureView,
        returnValueForMissingStub: _i35.VideoViewType.textureView,
      ) as _i35.VideoViewType);

  @override
  int get playerId => (super.noSuchMethod(
        Invocation.getter(#playerId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i20.Future<Duration?> get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _i20.Future<Duration?>.value(),
        returnValueForMissingStub: _i20.Future<Duration?>.value(),
      ) as _i20.Future<Duration?>);

  @override
  _i9.VideoPlayerValue get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeVideoPlayerValue_12(
          this,
          Invocation.getter(#value),
        ),
        returnValueForMissingStub: _FakeVideoPlayerValue_12(
          this,
          Invocation.getter(#value),
        ),
      ) as _i9.VideoPlayerValue);

  @override
  set value(_i9.VideoPlayerValue? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i20.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setLooping(bool? looping) => (super.noSuchMethod(
        Invocation.method(
          #setLooping,
          [looping],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> seekTo(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [position],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setPlaybackSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setPlaybackSpeed,
          [speed],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void setCaptionOffset(Duration? offset) => super.noSuchMethod(
        Invocation.method(
          #setCaptionOffset,
          [offset],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> setClosedCaptionFile(
          _i20.Future<_i36.ClosedCaptionFile>? closedCaptionFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClosedCaptionFile,
          [closedCaptionFile],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void removeListener(_i37.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i37.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserReviewsPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserReviewsPageCubit extends _i1.Mock
    implements _i38.UserReviewsPageCubit {
  @override
  int get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i20.Stream<int> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<int>.empty(),
        returnValueForMissingStub: _i20.Stream<int>.empty(),
      ) as _i20.Stream<int>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changePage(dynamic page) => super.noSuchMethod(
        Invocation.method(
          #changePage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(int? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i22.Change<int>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [DeleteItemReviewBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteItemReviewBloc extends _i1.Mock
    implements _i11.DeleteItemReviewBloc {
  @override
  _i10.DeleteItemReviewUseCase get deleteItemReviewUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#deleteItemReviewUseCase),
        returnValue: _FakeDeleteItemReviewUseCase_13(
          this,
          Invocation.getter(#deleteItemReviewUseCase),
        ),
        returnValueForMissingStub: _FakeDeleteItemReviewUseCase_13(
          this,
          Invocation.getter(#deleteItemReviewUseCase),
        ),
      ) as _i10.DeleteItemReviewUseCase);

  @override
  _i11.DeleteItemReviewState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDeleteItemReviewState_14(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDeleteItemReviewState_14(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.DeleteItemReviewState);

  @override
  _i20.Stream<_i11.DeleteItemReviewState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i11.DeleteItemReviewState>.empty(),
        returnValueForMissingStub:
            _i20.Stream<_i11.DeleteItemReviewState>.empty(),
      ) as _i20.Stream<_i11.DeleteItemReviewState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i11.DeleteItemReviewEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i11.DeleteItemReviewEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.DeleteItemReviewState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i11.DeleteItemReviewEvent>(
    _i22.EventHandler<E, _i11.DeleteItemReviewState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i11.DeleteItemReviewEvent,
                  _i11.DeleteItemReviewState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i11.DeleteItemReviewEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i11.DeleteItemReviewState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VoteOnReviewBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteOnReviewBloc extends _i1.Mock implements _i39.VoteOnReviewBloc {
  @override
  _i12.UpVoteItemReviewUseCase get upVoteItemReviewUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#upVoteItemReviewUseCase),
        returnValue: _FakeUpVoteItemReviewUseCase_15(
          this,
          Invocation.getter(#upVoteItemReviewUseCase),
        ),
        returnValueForMissingStub: _FakeUpVoteItemReviewUseCase_15(
          this,
          Invocation.getter(#upVoteItemReviewUseCase),
        ),
      ) as _i12.UpVoteItemReviewUseCase);

  @override
  _i13.DownVoteItemReviewUseCase get downVoteItemReviewUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#downVoteItemReviewUseCase),
        returnValue: _FakeDownVoteItemReviewUseCase_16(
          this,
          Invocation.getter(#downVoteItemReviewUseCase),
        ),
        returnValueForMissingStub: _FakeDownVoteItemReviewUseCase_16(
          this,
          Invocation.getter(#downVoteItemReviewUseCase),
        ),
      ) as _i13.DownVoteItemReviewUseCase);

  @override
  _i14.UpVoteRestaurantReviewUseCase get upVoteRestaurantReviewUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#upVoteRestaurantReviewUseCase),
        returnValue: _FakeUpVoteRestaurantReviewUseCase_17(
          this,
          Invocation.getter(#upVoteRestaurantReviewUseCase),
        ),
        returnValueForMissingStub: _FakeUpVoteRestaurantReviewUseCase_17(
          this,
          Invocation.getter(#upVoteRestaurantReviewUseCase),
        ),
      ) as _i14.UpVoteRestaurantReviewUseCase);

  @override
  _i15.DownVoteRestaurantReviewUseCase get downVoteRestaurantReviewUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#downVoteRestaurantReviewUseCase),
        returnValue: _FakeDownVoteRestaurantReviewUseCase_18(
          this,
          Invocation.getter(#downVoteRestaurantReviewUseCase),
        ),
        returnValueForMissingStub: _FakeDownVoteRestaurantReviewUseCase_18(
          this,
          Invocation.getter(#downVoteRestaurantReviewUseCase),
        ),
      ) as _i15.DownVoteRestaurantReviewUseCase);

  @override
  _i16.VoteOnReviewState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeVoteOnReviewState_19(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeVoteOnReviewState_19(
          this,
          Invocation.getter(#state),
        ),
      ) as _i16.VoteOnReviewState);

  @override
  _i20.Stream<_i16.VoteOnReviewState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i20.Stream<_i16.VoteOnReviewState>.empty(),
        returnValueForMissingStub: _i20.Stream<_i16.VoteOnReviewState>.empty(),
      ) as _i20.Stream<_i16.VoteOnReviewState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i40.VoteOnReviewEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i40.VoteOnReviewEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i16.VoteOnReviewState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i40.VoteOnReviewEvent>(
    _i22.EventHandler<E, _i16.VoteOnReviewState>? handler, {
    _i22.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i22.Transition<_i40.VoteOnReviewEvent, _i16.VoteOnReviewState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i40.VoteOnReviewEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void onChange(_i22.Change<_i16.VoteOnReviewState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UpVoteItemReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpVoteItemReviewUseCase extends _i1.Mock
    implements _i12.UpVoteItemReviewUseCase {
  @override
  _i17.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
        returnValueForMissingStub: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i17.VoteOnReviewRepository);

  @override
  _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>> call(
          _i43.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>);
}

/// A class which mocks [DownVoteItemReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownVoteItemReviewUseCase extends _i1.Mock
    implements _i13.DownVoteItemReviewUseCase {
  @override
  _i17.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
        returnValueForMissingStub: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i17.VoteOnReviewRepository);

  @override
  _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>> call(
          _i43.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>);
}

/// A class which mocks [UpVoteRestaurantReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpVoteRestaurantReviewUseCase extends _i1.Mock
    implements _i14.UpVoteRestaurantReviewUseCase {
  @override
  _i17.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
        returnValueForMissingStub: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i17.VoteOnReviewRepository);

  @override
  _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>> call(
          _i43.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>);
}

/// A class which mocks [DownVoteRestaurantReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownVoteRestaurantReviewUseCase extends _i1.Mock
    implements _i15.DownVoteRestaurantReviewUseCase {
  @override
  _i17.VoteOnReviewRepository get voteOnReviewRepository => (super.noSuchMethod(
        Invocation.getter(#voteOnReviewRepository),
        returnValue: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
        returnValueForMissingStub: _FakeVoteOnReviewRepository_20(
          this,
          Invocation.getter(#voteOnReviewRepository),
        ),
      ) as _i17.VoteOnReviewRepository);

  @override
  _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>> call(
          _i43.VoteOnReviewParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>.value(
                _FakeEither_21<_i41.Failure, _i42.VoteResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i20.Future<_i18.Either<_i41.Failure, _i42.VoteResponse>>);
}
