// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/item_detail/presentation/bloc/item_detail/item_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hive/hive.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:rateeat_mobile/src/core/core.dart' as _i7;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/item_detail/data/data_sources/local_item_detail_datasource.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/item_detail/domain/domain.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeItemRepository_0 extends _i1.SmartFake
    implements _i2.ItemRepository {
  _FakeItemRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_2<E> extends _i1.SmartFake implements _i4.Box<E> {
  _FakeBox_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItem_3 extends _i1.SmartFake implements _i5.Item {
  _FakeItem_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetItemUseCase extends _i1.Mock implements _i2.GetItemUseCase {
  @override
  _i2.ItemRepository get itemRepository => (super.noSuchMethod(
        Invocation.getter(#itemRepository),
        returnValue: _FakeItemRepository_0(
          this,
          Invocation.getter(#itemRepository),
        ),
        returnValueForMissingStub: _FakeItemRepository_0(
          this,
          Invocation.getter(#itemRepository),
        ),
      ) as _i2.ItemRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i5.Item>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, _i5.Item>>.value(
            _FakeEither_1<_i7.Failure, _i5.Item>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Either<_i7.Failure, _i5.Item>>.value(
                _FakeEither_1<_i7.Failure, _i5.Item>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i5.Item>>);
}

/// A class which mocks [LocalItemDetailDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalItemDetailDataSource extends _i1.Mock
    implements _i8.LocalItemDetailDataSource {
  @override
  int get maxItemDetail => (super.noSuchMethod(
        Invocation.getter(#maxItemDetail),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get itemDetailBoxName => (super.noSuchMethod(
        Invocation.getter(#itemDetailBoxName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#itemDetailBoxName),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#itemDetailBoxName),
        ),
      ) as String);

  @override
  String get popularItemReviewsBoxName => (super.noSuchMethod(
        Invocation.getter(#popularItemReviewsBoxName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#popularItemReviewsBoxName),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#popularItemReviewsBoxName),
        ),
      ) as String);

  @override
  String get recommendedItemsBoxName => (super.noSuchMethod(
        Invocation.getter(#recommendedItemsBoxName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#recommendedItemsBoxName),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#recommendedItemsBoxName),
        ),
      ) as String);

  @override
  _i4.Box<_i5.Item> get itemDetailBox => (super.noSuchMethod(
        Invocation.getter(#itemDetailBox),
        returnValue: _FakeBox_2<_i5.Item>(
          this,
          Invocation.getter(#itemDetailBox),
        ),
        returnValueForMissingStub: _FakeBox_2<_i5.Item>(
          this,
          Invocation.getter(#itemDetailBox),
        ),
      ) as _i4.Box<_i5.Item>);

  @override
  set itemDetailBox(_i4.Box<_i5.Item>? _itemDetailBox) => super.noSuchMethod(
        Invocation.setter(
          #itemDetailBox,
          _itemDetailBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Box<_i2.PopularItemReviewsResponse> get popularItemReviewsBox =>
      (super.noSuchMethod(
        Invocation.getter(#popularItemReviewsBox),
        returnValue: _FakeBox_2<_i2.PopularItemReviewsResponse>(
          this,
          Invocation.getter(#popularItemReviewsBox),
        ),
        returnValueForMissingStub: _FakeBox_2<_i2.PopularItemReviewsResponse>(
          this,
          Invocation.getter(#popularItemReviewsBox),
        ),
      ) as _i4.Box<_i2.PopularItemReviewsResponse>);

  @override
  set popularItemReviewsBox(
          _i4.Box<_i2.PopularItemReviewsResponse>? _popularItemReviewsBox) =>
      super.noSuchMethod(
        Invocation.setter(
          #popularItemReviewsBox,
          _popularItemReviewsBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Box<String> get recommendedItemsBox => (super.noSuchMethod(
        Invocation.getter(#recommendedItemsBox),
        returnValue: _FakeBox_2<String>(
          this,
          Invocation.getter(#recommendedItemsBox),
        ),
        returnValueForMissingStub: _FakeBox_2<String>(
          this,
          Invocation.getter(#recommendedItemsBox),
        ),
      ) as _i4.Box<String>);

  @override
  set recommendedItemsBox(_i4.Box<String>? _recommendedItemsBox) =>
      super.noSuchMethod(
        Invocation.setter(
          #recommendedItemsBox,
          _recommendedItemsBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i5.Item> getItemDetail(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #getItemDetail,
          [itemId],
        ),
        returnValue: _i6.Future<_i5.Item>.value(_FakeItem_3(
          this,
          Invocation.method(
            #getItemDetail,
            [itemId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i5.Item>.value(_FakeItem_3(
          this,
          Invocation.method(
            #getItemDetail,
            [itemId],
          ),
        )),
      ) as _i6.Future<_i5.Item>);

  @override
  _i6.Future<void> saveItemDetail(_i5.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #saveItemDetail,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteItemDetail(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItemDetail,
          [itemId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.PopularItemReviewsResponse?> getPopularItemReviews(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularItemReviews,
          [itemId],
        ),
        returnValue: _i6.Future<_i2.PopularItemReviewsResponse?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i2.PopularItemReviewsResponse?>.value(),
      ) as _i6.Future<_i2.PopularItemReviewsResponse?>);

  @override
  _i6.Future<void> savePopularItemReviews(
    String? itemId,
    _i2.PopularItemReviewsResponse? reviews,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePopularItemReviews,
          [
            itemId,
            reviews,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deletePopularItemReviews(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePopularItemReviews,
          [itemId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.Item>?> getRecommendedItems(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedItems,
          [itemId],
        ),
        returnValue: _i6.Future<List<_i5.Item>?>.value(),
        returnValueForMissingStub: _i6.Future<List<_i5.Item>?>.value(),
      ) as _i6.Future<List<_i5.Item>?>);

  @override
  _i6.Future<void> saveRecommendedItems(
    String? itemId,
    List<_i5.Item>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecommendedItems,
          [
            itemId,
            items,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRecommendedItems(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecommendedItems,
          [itemId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
