// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/live_search/presentation/bloc/local_search_history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i6;
import 'package:rateeat_mobile/src/features/live_search/data/models/history.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/live_search/domain/repository/live_search_repo.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/add_history_use_case.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/clear_history_use_case.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/delete_history_use_case.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/get_history_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLiveSearchRepository_0 extends _i1.SmartFake
    implements _i2.LiveSearchRepository {
  _FakeLiveSearchRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddLocalSearchHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddLocalSearchHistoryUseCase extends _i1.Mock
    implements _i4.AddLocalSearchHistoryUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i4.AddLocalSearchUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [ClearLocalHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearLocalHistoryUseCase extends _i1.Mock
    implements _i7.ClearLocalHistoryUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.ClearLocalHistoryUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteLocalHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteLocalHistoryUseCase extends _i1.Mock
    implements _i8.DeleteLocalHistoryUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i8.DeleteHistoryUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetLocalHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocalHistoryUseCase extends _i1.Mock
    implements _i9.GetLocalHistoryUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i10.History>>> call(
          _i9.GetHistoryUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i10.History>>>.value(
                _FakeEither_1<_i6.Failure, List<_i10.History>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i10.History>>>.value(
                _FakeEither_1<_i6.Failure, List<_i10.History>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i10.History>>>);
}
