// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/live_search/presentation/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i6;
import 'package:rateeat_mobile/src/features/discover_item/data/models/search_result.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/live_search/domain/repository/live_search_repo.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/search_items_use_case.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/live_search/domain/use_case/search_restaurants_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLiveSearchRepository_0 extends _i1.SmartFake
    implements _i2.LiveSearchRepository {
  _FakeLiveSearchRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LiveSearchItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSearchItemsUseCase extends _i1.Mock
    implements _i4.LiveSearchItemsUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Item>>> call(
          _i4.LiveSearchItemsUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Item>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Item>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Item>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Item>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Item>>>);
}

/// A class which mocks [LiveSearchRestaurantsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSearchRestaurantsUseCase extends _i1.Mock
    implements _i8.LiveSearchRestaurantsUseCase {
  @override
  _i2.LiveSearchRepository get liveSearchRepository => (super.noSuchMethod(
        Invocation.getter(#liveSearchRepository),
        returnValue: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
        returnValueForMissingStub: _FakeLiveSearchRepository_0(
          this,
          Invocation.getter(#liveSearchRepository),
        ),
      ) as _i2.LiveSearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.RestaurantResult>>> call(
          String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i9.RestaurantResult>>>.value(
            _FakeEither_1<_i6.Failure, List<_i9.RestaurantResult>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i3.Either<_i6.Failure, List<_i9.RestaurantResult>>>.value(
            _FakeEither_1<_i6.Failure, List<_i9.RestaurantResult>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.RestaurantResult>>>);
}
