// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/homepage/presentation/pages/homepage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:dartz/dartz.dart' as _i21;
import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:rateeat_mobile/src/core/core.dart' as _i7;
import 'package:rateeat_mobile/src/core/hive/local_user_model.dart' as _i23;
import 'package:rateeat_mobile/src/features/discover_item/domain/use_cases/nearby_usecase.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/nearby/near_by_rest_bloc.dart'
    as _i17;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/nearby/near_by_rest_event.dart'
    as _i18;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/nearby/nearby_rest_state.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/features.dart' as _i2;
import 'package:rateeat_mobile/src/features/homepage/presentation/bloc/highest_rated/popular_event.dart'
    as _i16;
import 'package:rateeat_mobile/src/features/homepage/presentation/bloc/highest_rated/popular_state.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/homepage/presentation/bloc/tag/tag_bloc.dart'
    as _i19;
import 'package:rateeat_mobile/src/features/homepage/presentation/bloc/tag/tag_event.dart'
    as _i20;
import 'package:rateeat_mobile/src/features/homepage/presentation/bloc/tag/tag_state.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/location_search/domain/usecases/get_location_description_usecase.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/location_search/presentation/bloc/location_description/location_description_bloc.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/map_section/presentation/widgets/google_map_content.dart'
    as _i24;
import 'package:rateeat_mobile/src/features/notification/domain/use_cases/get_un_read_notifications_count_use_case.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/notification/presentation/bloc/un_read_notification_counter/un_read_notification_counter_bloc.dart'
    as _i11;
import 'package:rateeat_mobile/src/features/order_history/domain/usecases/orders_count_usecase.dart'
    as _i12;
import 'package:rateeat_mobile/src/features/order_history/presentation/bloc/orders_count/order_count_bloc.dart'
    as _i13;
import 'package:rateeat_mobile/src/features/user_profile/user_profile.dart'
    as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetPopularUseCase_0 extends _i1.SmartFake
    implements _i2.GetPopularUseCase {
  _FakeGetPopularUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePopularState_1 extends _i1.SmartFake implements _i3.PopularState {
  _FakePopularState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRestaurantRecommendationsUseCase_2 extends _i1.SmartFake
    implements _i2.GetRestaurantRecommendationsUseCase {
  _FakeGetRestaurantRecommendationsUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecommendedState_3 extends _i1.SmartFake
    implements _i2.RecommendedState {
  _FakeRecommendedState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNearbyUseCase_4 extends _i1.SmartFake implements _i4.NearbyUseCase {
  _FakeNearbyUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomePageNearbyRestaurantState_5 extends _i1.SmartFake
    implements _i5.HomePageNearbyRestaurantState {
  _FakeHomePageNearbyRestaurantState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectedTagState_6 extends _i1.SmartFake
    implements _i6.SelectedTagState {
  _FakeSelectedTagState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationUseCase_7 extends _i1.SmartFake
    implements _i2.GetLocationUseCase {
  _FakeGetLocationUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserLocationState_8 extends _i1.SmartFake
    implements _i2.UserLocationState {
  _FakeUserLocationState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkState_9 extends _i1.SmartFake implements _i7.NetworkState {
  _FakeNetworkState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeTagSuggestionUseCase_10 extends _i1.SmartFake
    implements _i2.GeTagSuggestionUseCase {
  _FakeGeTagSuggestionUseCase_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchFoodCategoryUseCase_11 extends _i1.SmartFake
    implements _i2.SearchFoodCategoryUseCase {
  _FakeSearchFoodCategoryUseCase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchFoodCategoryState_12 extends _i1.SmartFake
    implements _i2.SearchFoodCategoryState {
  _FakeSearchFoodCategoryState_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationDescriptionUseCase_13 extends _i1.SmartFake
    implements _i8.GetLocationDescriptionUseCase {
  _FakeGetLocationDescriptionUseCase_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationDescriptionState_14 extends _i1.SmartFake
    implements _i9.LocationDescriptionState {
  _FakeLocationDescriptionState_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetUnreadNotificationsCountUseCase_15 extends _i1.SmartFake
    implements _i10.GetUnreadNotificationsCountUseCase {
  _FakeGetUnreadNotificationsCountUseCase_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnreadNotificationsCounterState_16 extends _i1.SmartFake
    implements _i11.UnreadNotificationsCounterState {
  _FakeUnreadNotificationsCounterState_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetchOrdersCountUseCase_17 extends _i1.SmartFake
    implements _i12.FetchOrdersCountUseCase {
  _FakeFetchOrdersCountUseCase_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrdersCountState_18 extends _i1.SmartFake
    implements _i13.OrdersCountState {
  _FakeOrdersCountState_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PopularBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularBloc extends _i1.Mock implements _i2.PopularBloc {
  @override
  _i2.GetPopularUseCase get getPopularUseCase => (super.noSuchMethod(
        Invocation.getter(#getPopularUseCase),
        returnValue: _FakeGetPopularUseCase_0(
          this,
          Invocation.getter(#getPopularUseCase),
        ),
        returnValueForMissingStub: _FakeGetPopularUseCase_0(
          this,
          Invocation.getter(#getPopularUseCase),
        ),
      ) as _i2.GetPopularUseCase);

  @override
  _i3.PopularState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePopularState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePopularState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.PopularState);

  @override
  _i14.Stream<_i3.PopularState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i3.PopularState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i3.PopularState>.empty(),
      ) as _i14.Stream<_i3.PopularState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void reset(_i15.Emitter<dynamic>? emit) => super.noSuchMethod(
        Invocation.method(
          #reset,
          [emit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i16.PopularEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i16.PopularEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.PopularState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i16.PopularEvent>(
    _i15.EventHandler<E, _i3.PopularState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i16.PopularEvent, _i3.PopularState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i16.PopularEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i3.PopularState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecommendedBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendedBloc extends _i1.Mock implements _i2.RecommendedBloc {
  @override
  _i2.GetRestaurantRecommendationsUseCase get getRecommendedUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getRecommendedUseCase),
        returnValue: _FakeGetRestaurantRecommendationsUseCase_2(
          this,
          Invocation.getter(#getRecommendedUseCase),
        ),
        returnValueForMissingStub: _FakeGetRestaurantRecommendationsUseCase_2(
          this,
          Invocation.getter(#getRecommendedUseCase),
        ),
      ) as _i2.GetRestaurantRecommendationsUseCase);

  @override
  _i2.RecommendedState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRecommendedState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeRecommendedState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.RecommendedState);

  @override
  _i14.Stream<_i2.RecommendedState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i2.RecommendedState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i2.RecommendedState>.empty(),
      ) as _i14.Stream<_i2.RecommendedState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i2.RecommendedEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.RecommendedEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.RecommendedState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.RecommendedEvent>(
    _i15.EventHandler<E, _i2.RecommendedState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i2.RecommendedEvent, _i2.RecommendedState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.RecommendedEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i2.RecommendedState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HomePageNearbyRestaurantBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomePageNearbyRestaurantBloc extends _i1.Mock
    implements _i17.HomePageNearbyRestaurantBloc {
  @override
  _i4.NearbyUseCase get nearbyUseCase => (super.noSuchMethod(
        Invocation.getter(#nearbyUseCase),
        returnValue: _FakeNearbyUseCase_4(
          this,
          Invocation.getter(#nearbyUseCase),
        ),
        returnValueForMissingStub: _FakeNearbyUseCase_4(
          this,
          Invocation.getter(#nearbyUseCase),
        ),
      ) as _i4.NearbyUseCase);

  @override
  _i5.HomePageNearbyRestaurantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomePageNearbyRestaurantState_5(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeHomePageNearbyRestaurantState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.HomePageNearbyRestaurantState);

  @override
  _i14.Stream<_i5.HomePageNearbyRestaurantState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i5.HomePageNearbyRestaurantState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i5.HomePageNearbyRestaurantState>.empty(),
      ) as _i14.Stream<_i5.HomePageNearbyRestaurantState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void add(_i18.HomePageNearbyRestEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i18.HomePageNearbyRestEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.HomePageNearbyRestaurantState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i18.HomePageNearbyRestEvent>(
    _i15.EventHandler<E, _i5.HomePageNearbyRestaurantState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i18.HomePageNearbyRestEvent,
                  _i5.HomePageNearbyRestaurantState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i18.HomePageNearbyRestEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<_i5.HomePageNearbyRestaurantState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TagBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagBloc extends _i1.Mock implements _i19.TagBloc {
  @override
  _i6.SelectedTagState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSelectedTagState_6(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSelectedTagState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.SelectedTagState);

  @override
  _i14.Stream<_i6.SelectedTagState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i6.SelectedTagState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i6.SelectedTagState>.empty(),
      ) as _i14.Stream<_i6.SelectedTagState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i20.TagEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i20.TagEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.SelectedTagState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i20.TagEvent>(
    _i15.EventHandler<E, _i6.SelectedTagState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i20.TagEvent, _i6.SelectedTagState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i20.TagEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i6.SelectedTagState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserLocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocationBloc extends _i1.Mock implements _i2.UserLocationBloc {
  @override
  _i2.GetLocationUseCase get getLocationUseCase => (super.noSuchMethod(
        Invocation.getter(#getLocationUseCase),
        returnValue: _FakeGetLocationUseCase_7(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
        returnValueForMissingStub: _FakeGetLocationUseCase_7(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
      ) as _i2.GetLocationUseCase);

  @override
  _i2.UserLocationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserLocationState_8(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserLocationState_8(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.UserLocationState);

  @override
  _i14.Stream<_i2.UserLocationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i2.UserLocationState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i2.UserLocationState>.empty(),
      ) as _i14.Stream<_i2.UserLocationState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.UserLocationState fromEither(
          _i21.Either<_i7.Failure, _i2.Location>? eitherFailureOrLocation) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromEither,
          [eitherFailureOrLocation],
        ),
        returnValue: _FakeUserLocationState_8(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
        returnValueForMissingStub: _FakeUserLocationState_8(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
      ) as _i2.UserLocationState);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void add(_i2.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.UserLocationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.UserLocationEvent>(
    _i15.EventHandler<E, _i2.UserLocationState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i2.UserLocationEvent, _i2.UserLocationState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.UserLocationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<_i2.UserLocationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NetworkBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkBloc extends _i1.Mock implements _i7.NetworkBloc {
  @override
  _i7.NetworkState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNetworkState_9(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeNetworkState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.NetworkState);

  @override
  _i14.Stream<_i7.NetworkState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i7.NetworkState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i7.NetworkState>.empty(),
      ) as _i14.Stream<_i7.NetworkState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i7.NetworkEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i7.NetworkEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i7.NetworkState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i7.NetworkEvent>(
    _i15.EventHandler<E, _i7.NetworkState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i7.NetworkEvent, _i7.NetworkState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i7.NetworkEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i7.NetworkState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SearchFoodCategoryBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchFoodCategoryBloc extends _i1.Mock
    implements _i2.SearchFoodCategoryBloc {
  @override
  _i2.GeTagSuggestionUseCase get geTagSuggestionUseCase => (super.noSuchMethod(
        Invocation.getter(#geTagSuggestionUseCase),
        returnValue: _FakeGeTagSuggestionUseCase_10(
          this,
          Invocation.getter(#geTagSuggestionUseCase),
        ),
        returnValueForMissingStub: _FakeGeTagSuggestionUseCase_10(
          this,
          Invocation.getter(#geTagSuggestionUseCase),
        ),
      ) as _i2.GeTagSuggestionUseCase);

  @override
  _i2.SearchFoodCategoryUseCase get searchFoodCategoryUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#searchFoodCategoryUseCase),
        returnValue: _FakeSearchFoodCategoryUseCase_11(
          this,
          Invocation.getter(#searchFoodCategoryUseCase),
        ),
        returnValueForMissingStub: _FakeSearchFoodCategoryUseCase_11(
          this,
          Invocation.getter(#searchFoodCategoryUseCase),
        ),
      ) as _i2.SearchFoodCategoryUseCase);

  @override
  _i2.SearchFoodCategoryState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSearchFoodCategoryState_12(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSearchFoodCategoryState_12(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.SearchFoodCategoryState);

  @override
  _i14.Stream<_i2.SearchFoodCategoryState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i2.SearchFoodCategoryState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i2.SearchFoodCategoryState>.empty(),
      ) as _i14.Stream<_i2.SearchFoodCategoryState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i2.SearchFoodCategoryEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.SearchFoodCategoryEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.SearchFoodCategoryState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.SearchFoodCategoryEvent>(
    _i15.EventHandler<E, _i2.SearchFoodCategoryState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i2.SearchFoodCategoryEvent,
                  _i2.SearchFoodCategoryState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.SearchFoodCategoryEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i2.SearchFoodCategoryState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalSource extends _i1.Mock
    implements _i2.AuthenticationLocalSource {
  @override
  _i14.Future<void> cacheUserCredential({required _i22.UserModel? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserCredential,
          [],
          {#user: user},
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> updateUserCredential(
          {required _i23.LocalUserModel? updatedUserInformation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCredential,
          [],
          {#updatedUserInformation: updatedUserInformation},
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> clearUserCredential() => (super.noSuchMethod(
        Invocation.method(
          #clearUserCredential,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<bool> getAppInitialization() => (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i14.Future<bool>.value(false),
        returnValueForMissingStub: _i14.Future<bool>.value(false),
      ) as _i14.Future<bool>);
}

/// A class which mocks [LocationDescriptionBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationDescriptionBloc extends _i1.Mock
    implements _i9.LocationDescriptionBloc {
  @override
  _i8.GetLocationDescriptionUseCase get getLocationDescriptionUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getLocationDescriptionUseCase),
        returnValue: _FakeGetLocationDescriptionUseCase_13(
          this,
          Invocation.getter(#getLocationDescriptionUseCase),
        ),
        returnValueForMissingStub: _FakeGetLocationDescriptionUseCase_13(
          this,
          Invocation.getter(#getLocationDescriptionUseCase),
        ),
      ) as _i8.GetLocationDescriptionUseCase);

  @override
  _i9.LocationDescriptionState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeLocationDescriptionState_14(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeLocationDescriptionState_14(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.LocationDescriptionState);

  @override
  _i14.Stream<_i9.LocationDescriptionState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i9.LocationDescriptionState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i9.LocationDescriptionState>.empty(),
      ) as _i14.Stream<_i9.LocationDescriptionState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i9.LocationDescriptionEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i9.LocationDescriptionEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.LocationDescriptionState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i9.LocationDescriptionEvent>(
    _i15.EventHandler<E, _i9.LocationDescriptionState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i9.LocationDescriptionEvent,
                  _i9.LocationDescriptionState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i9.LocationDescriptionEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i9.LocationDescriptionState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UnreadNotificationsCounterBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnreadNotificationsCounterBloc extends _i1.Mock
    implements _i11.UnreadNotificationsCounterBloc {
  @override
  _i10.GetUnreadNotificationsCountUseCase
      get getUnReadNotificationsCountUseCase => (super.noSuchMethod(
            Invocation.getter(#getUnReadNotificationsCountUseCase),
            returnValue: _FakeGetUnreadNotificationsCountUseCase_15(
              this,
              Invocation.getter(#getUnReadNotificationsCountUseCase),
            ),
            returnValueForMissingStub:
                _FakeGetUnreadNotificationsCountUseCase_15(
              this,
              Invocation.getter(#getUnReadNotificationsCountUseCase),
            ),
          ) as _i10.GetUnreadNotificationsCountUseCase);

  @override
  _i11.UnreadNotificationsCounterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUnreadNotificationsCounterState_16(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUnreadNotificationsCounterState_16(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.UnreadNotificationsCounterState);

  @override
  _i14.Stream<_i11.UnreadNotificationsCounterState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i11.UnreadNotificationsCounterState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i11.UnreadNotificationsCounterState>.empty(),
      ) as _i14.Stream<_i11.UnreadNotificationsCounterState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i11.UnreadNotificationsCounterEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i11.UnreadNotificationsCounterEvent? event) =>
      super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.UnreadNotificationsCounterState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i11.UnreadNotificationsCounterEvent>(
    _i15.EventHandler<E, _i11.UnreadNotificationsCounterState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i11.UnreadNotificationsCounterEvent,
                  _i11.UnreadNotificationsCounterState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i11.UnreadNotificationsCounterEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i11.UnreadNotificationsCounterState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HomeFastingToggleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeFastingToggleBloc extends _i1.Mock
    implements _i2.HomeFastingToggleBloc {
  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i14.Stream<bool> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<bool>.empty(),
        returnValueForMissingStub: _i14.Stream<bool>.empty(),
      ) as _i14.Stream<bool>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void emit(bool? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<bool>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [SearchQueryCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchQueryCubit extends _i1.Mock implements _i24.SearchQueryCubit {
  @override
  String get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as String);

  @override
  _i14.Stream<String> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<String>.empty(),
        returnValueForMissingStub: _i14.Stream<String>.empty(),
      ) as _i14.Stream<String>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #updateQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(String? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<String>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [OrdersCountBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersCountBloc extends _i1.Mock implements _i13.OrdersCountBloc {
  @override
  _i12.FetchOrdersCountUseCase get fetchOrdersCountUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#fetchOrdersCountUseCase),
        returnValue: _FakeFetchOrdersCountUseCase_17(
          this,
          Invocation.getter(#fetchOrdersCountUseCase),
        ),
        returnValueForMissingStub: _FakeFetchOrdersCountUseCase_17(
          this,
          Invocation.getter(#fetchOrdersCountUseCase),
        ),
      ) as _i12.FetchOrdersCountUseCase);

  @override
  _i13.OrdersCountState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrdersCountState_18(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeOrdersCountState_18(
          this,
          Invocation.getter(#state),
        ),
      ) as _i13.OrdersCountState);

  @override
  _i14.Stream<_i13.OrdersCountState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i13.OrdersCountState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i13.OrdersCountState>.empty(),
      ) as _i14.Stream<_i13.OrdersCountState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i13.OrdersCountEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i13.OrdersCountEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i13.OrdersCountState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i13.OrdersCountEvent>(
    _i15.EventHandler<E, _i13.OrdersCountState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i13.OrdersCountEvent, _i13.OrdersCountState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i13.OrdersCountEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i13.OrdersCountState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
