// ignore_for_file: overridden_fields
// ? TODO: move the hive up to the entity layer

import 'package:hive/hive.dart';
import 'package:rateeat_mobile/src/features/restaurant_detail/data/models/popular_restaurant_review_response_model.dart';
import 'package:rateeat_mobile/src/features/restaurant_detail/domain/entities/popular_restaurant_reviews_response.dart';

part 'popular_restaurant_reviews_response_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 23) // Make sure to use a unique typeId for each model
class PopularRestaurantReviewsResponseModel
    extends PopularRestaurantReviewsResponse {
  @override
  @HiveField(0)
  final List<PopularRestaurantReviewResponseModel> reviews;

  @override
  @HiveField(1)
  final List<int> ratingsCount;

  @override
  @HiveField(2)
  final double averageRating;

  @override
  @HiveField(3)
  final int numberOfReviews;

  // Constructor
  const PopularRestaurantReviewsResponseModel({
    required this.reviews,
    required this.ratingsCount,
    required this.averageRating,
    required this.numberOfReviews,
  }) : super(
          reviews: reviews,
          ratingsCount: ratingsCount,
          averageRating: averageRating,
          numberOfReviews: numberOfReviews,
        );

  // Factory method for fromJson
  factory PopularRestaurantReviewsResponseModel.fromJson(
      Map<String, dynamic> json) {
    return PopularRestaurantReviewsResponseModel(
      reviews: (json['restaurantReviews'] as List<dynamic>)
          .map<PopularRestaurantReviewResponseModel>(
            (review) => PopularRestaurantReviewResponseModel.fromMap(review),
          )
          .toList(),
      ratingsCount: getRatingCount(json['ratingCount']),
      averageRating: json['avgRating'] != null
          ? double.parse(
              (json['avgRating'].toDouble() ?? 0.0).toStringAsFixed(2))
          : 0.0,
      numberOfReviews: json['numReviews'] ?? 0,
    );
  }

  // Map conversion method to JSON
  @override
  Map<String, dynamic> toJson() {
    return {
      'restaurantReviews': reviews.map((review) => review.toMap()).toList(),
      'ratingCount': {
        'one_star_count': ratingsCount[0],
        'two_star_count': ratingsCount[1],
        'three_star_count': ratingsCount[2],
        'four_star_count': ratingsCount[3],
        'five_star_count': ratingsCount[4],
      },
      'avgRating': averageRating,
      'numReviews': numberOfReviews,
    };
  }
}

List<int> getRatingCount(Map<String, dynamic> json) => [
      json['one_star_count'] ?? 0,
      json['two_star_count'] ?? 0,
      json['three_star_count'] ?? 0,
      json['four_star_count'] ?? 0,
      json['five_star_count'] ?? 0,
    ];
