// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/map_section/data/repositories/location_based_restaurants_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/map_section/data/data_sources/location_based_restaurants_dp.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocationRestaurantsRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRestaurantsRemoteSource extends _i1.Mock
    implements _i2.LocationRestaurantsRemoteSource {
  @override
  _i3.Future<int> getRestaurantsBasedOnLocation({
    required double? lat,
    required double? long,
    required double? radius,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantsBasedOnLocation,
          [],
          {
            #lat: lat,
            #long: long,
            #radius: radius,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
