// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/discover_item/presentation/widgetTest/discover_item_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:dartz/dartz.dart' as _i22;
import 'package:firebase_analytics/firebase_analytics.dart' as _i8;
import 'package:flutter/material.dart' as _i20;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:rateeat_mobile/src/core/core.dart' as _i23;
import 'package:rateeat_mobile/src/core/hive/local_user_model.dart' as _i19;
import 'package:rateeat_mobile/src/core/hive/user_engagement_analytics.dart'
    as _i21;
import 'package:rateeat_mobile/src/features/discover_item/domain/use_cases/filer_page_usecase.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/discover_item/domain/use_cases/nearby_usecase.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/discover_item/domain/use_cases/search_page_use_case.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/filter/filter_items_event.dart'
    as _i16;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/filter/filter_items_state.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/nearby/near_by_rest_event.dart'
    as _i17;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/nearby/nearby_rest_state.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/search/search_restaurant_event.dart'
    as _i13;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/search/search_restaurant_state.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/search/selected_restaurant_event.dart'
    as _i24;
import 'package:rateeat_mobile/src/features/discover_item/presentation/bloc/search/selected_restaurant_state.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/features.dart' as _i9;
import 'package:rateeat_mobile/src/features/user_profile/user_profile.dart'
    as _i18;

import 'discover_item_widget_test.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchPageUseCase_0 extends _i1.SmartFake
    implements _i2.SearchPageUseCase {
  _FakeSearchPageUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchRestaurantState_1 extends _i1.SmartFake
    implements _i3.SearchRestaurantState {
  _FakeSearchRestaurantState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterItemsUseCase_2 extends _i1.SmartFake
    implements _i4.FilterItemsUseCase {
  _FakeFilterItemsUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilterItemsState_3 extends _i1.SmartFake
    implements _i5.FilterItemsState {
  _FakeFilterItemsState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNearbyUseCase_4 extends _i1.SmartFake implements _i6.NearbyUseCase {
  _FakeNearbyUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomePageNearbyRestaurantState_5 extends _i1.SmartFake
    implements _i7.HomePageNearbyRestaurantState {
  _FakeHomePageNearbyRestaurantState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalyticsObserver_6 extends _i1.SmartFake
    implements _i8.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLocationUseCase_7 extends _i1.SmartFake
    implements _i9.GetLocationUseCase {
  _FakeGetLocationUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserLocationState_8 extends _i1.SmartFake
    implements _i9.UserLocationState {
  _FakeUserLocationState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectedRestaurantState_9 extends _i1.SmartFake
    implements _i10.SelectedRestaurantState {
  _FakeSelectedRestaurantState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockSearchRestaurantsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockSearchRestaurantsBloc extends _i1.Mock
    implements _i11.MockSearchRestaurantsBloc {
  @override
  _i2.SearchPageUseCase get searchPageUseCase => (super.noSuchMethod(
        Invocation.getter(#searchPageUseCase),
        returnValue: _FakeSearchPageUseCase_0(
          this,
          Invocation.getter(#searchPageUseCase),
        ),
        returnValueForMissingStub: _FakeSearchPageUseCase_0(
          this,
          Invocation.getter(#searchPageUseCase),
        ),
      ) as _i2.SearchPageUseCase);

  @override
  _i3.SearchRestaurantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSearchRestaurantState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSearchRestaurantState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SearchRestaurantState);

  @override
  _i12.Stream<_i3.SearchRestaurantState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i3.SearchRestaurantState>.empty(),
        returnValueForMissingStub:
            _i12.Stream<_i3.SearchRestaurantState>.empty(),
      ) as _i12.Stream<_i3.SearchRestaurantState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i13.SearchRestaurantEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i13.SearchRestaurantEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.SearchRestaurantState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i13.SearchRestaurantEvent>(
    _i14.EventHandler<E, _i3.SearchRestaurantState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i13.SearchRestaurantEvent,
                  _i3.SearchRestaurantState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i13.SearchRestaurantEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i14.Change<_i3.SearchRestaurantState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockDiscoverMenuPriceSelectorCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockDiscoverMenuPriceSelectorCubit extends _i1.Mock
    implements _i11.MockDiscoverMenuPriceSelectorCubit {
  @override
  String get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as String);

  @override
  _i12.Stream<String> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<String>.empty(),
        returnValueForMissingStub: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changePrice(String? value) => super.noSuchMethod(
        Invocation.method(
          #changePrice,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(String? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<String>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [MockDiscoverMenuItemSelectorCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockDiscoverMenuItemSelectorCubit extends _i1.Mock
    implements _i11.MockDiscoverMenuItemSelectorCubit {
  @override
  double get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i12.Stream<double> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<double>.empty(),
        returnValueForMissingStub: _i12.Stream<double>.empty(),
      ) as _i12.Stream<double>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changeRating(double? value) => super.noSuchMethod(
        Invocation.method(
          #changeRating,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(double? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<double>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [MockDiscoverItemPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockDiscoverItemPageCubit extends _i1.Mock
    implements _i11.MockDiscoverItemPageCubit {
  @override
  int get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i12.Stream<int> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<int>.empty(),
        returnValueForMissingStub: _i12.Stream<int>.empty(),
      ) as _i12.Stream<int>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changePage(dynamic page) => super.noSuchMethod(
        Invocation.method(
          #changePage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(int? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<int>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [MockFilterItemsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockFilterItemsBloc extends _i1.Mock
    implements _i11.MockFilterItemsBloc {
  @override
  _i4.FilterItemsUseCase get filterItemsUseCase => (super.noSuchMethod(
        Invocation.getter(#filterItemsUseCase),
        returnValue: _FakeFilterItemsUseCase_2(
          this,
          Invocation.getter(#filterItemsUseCase),
        ),
        returnValueForMissingStub: _FakeFilterItemsUseCase_2(
          this,
          Invocation.getter(#filterItemsUseCase),
        ),
      ) as _i4.FilterItemsUseCase);

  @override
  _i5.FilterItemsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFilterItemsState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeFilterItemsState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.FilterItemsState);

  @override
  _i12.Stream<_i5.FilterItemsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i5.FilterItemsState>.empty(),
        returnValueForMissingStub: _i12.Stream<_i5.FilterItemsState>.empty(),
      ) as _i12.Stream<_i5.FilterItemsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i16.FilterItemsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i16.FilterItemsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.FilterItemsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i16.FilterItemsEvent>(
    _i14.EventHandler<E, _i5.FilterItemsState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i16.FilterItemsEvent, _i5.FilterItemsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i16.FilterItemsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i14.Change<_i5.FilterItemsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockHomePageNearByBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockHomePageNearByBloc extends _i1.Mock
    implements _i11.MockHomePageNearByBloc {
  @override
  _i6.NearbyUseCase get nearbyUseCase => (super.noSuchMethod(
        Invocation.getter(#nearbyUseCase),
        returnValue: _FakeNearbyUseCase_4(
          this,
          Invocation.getter(#nearbyUseCase),
        ),
        returnValueForMissingStub: _FakeNearbyUseCase_4(
          this,
          Invocation.getter(#nearbyUseCase),
        ),
      ) as _i6.NearbyUseCase);

  @override
  _i7.HomePageNearbyRestaurantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomePageNearbyRestaurantState_5(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeHomePageNearbyRestaurantState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.HomePageNearbyRestaurantState);

  @override
  _i12.Stream<_i7.HomePageNearbyRestaurantState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i7.HomePageNearbyRestaurantState>.empty(),
        returnValueForMissingStub:
            _i12.Stream<_i7.HomePageNearbyRestaurantState>.empty(),
      ) as _i12.Stream<_i7.HomePageNearbyRestaurantState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void add(_i17.HomePageNearbyRestEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i17.HomePageNearbyRestEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i7.HomePageNearbyRestaurantState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i17.HomePageNearbyRestEvent>(
    _i14.EventHandler<E, _i7.HomePageNearbyRestaurantState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i17.HomePageNearbyRestEvent,
                  _i7.HomePageNearbyRestaurantState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i17.HomePageNearbyRestEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<_i7.HomePageNearbyRestaurantState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockAuthenticationLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAuthenticationLocalSource extends _i1.Mock
    implements _i11.MockAuthenticationLocalSource {
  @override
  _i12.Future<void> cacheUserCredential({required _i18.UserModel? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserCredential,
          [],
          {#user: user},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateUserCredential(
          {required _i19.LocalUserModel? updatedUserInformation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCredential,
          [],
          {#updatedUserInformation: updatedUserInformation},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> clearUserCredential() => (super.noSuchMethod(
        Invocation.method(
          #clearUserCredential,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<bool> getAppInitialization() => (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
        returnValueForMissingStub: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [MockLocalAnalyticsObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockLocalAnalyticsObserver extends _i1.Mock
    implements _i11.MockLocalAnalyticsObserver {
  @override
  void didPush(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> clearSessionAnalyticsData() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionAnalyticsData,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateUserEngagementAnalytics(
          {required _i21.UserEngagementAnalytics? update}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserEngagementAnalytics,
          [],
          {#update: update},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateItemAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateRestaurantAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateRestaurantSearchAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantSearchAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateItemSearchAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemSearchAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateRestaurantShareAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRestaurantShareAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateItemShareAnalytics(
          {required Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemShareAnalytics,
          [],
          {#params: params},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void didPop(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i20.Route<dynamic>? newRoute,
    _i20.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i20.Route<dynamic>? topRoute,
    _i20.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockAnalyticsObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAnalyticsObserver extends _i1.Mock
    implements _i11.MockAnalyticsObserver {
  @override
  _i8.FirebaseAnalyticsObserver getAnalyticsObserver() => (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsObserver,
          [],
        ),
        returnValue: _FakeFirebaseAnalyticsObserver_6(
          this,
          Invocation.method(
            #getAnalyticsObserver,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFirebaseAnalyticsObserver_6(
          this,
          Invocation.method(
            #getAnalyticsObserver,
            [],
          ),
        ),
      ) as _i8.FirebaseAnalyticsObserver);

  @override
  void didPush(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> logLogin({
    required String? method,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logLogin,
          [],
          {
            #method: method,
            #params: params,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> logSignUp({
    required String? method,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSignUp,
          [],
          {
            #method: method,
            #params: params,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> sendAnalyticsEvent({
    required String? eventName,
    required Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAnalyticsEvent,
          [],
          {
            #eventName: eventName,
            #params: params,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setUserId({required String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [],
          {#userId: userId},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [],
          {
            #name: name,
            #value: value,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setAnalyticsCollectionEnabled() => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsCollectionEnabled,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setAppInstanceId() => (super.noSuchMethod(
        Invocation.method(
          #setAppInstanceId,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> resetAnalyticsData() => (super.noSuchMethod(
        Invocation.method(
          #resetAnalyticsData,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void didPop(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i20.Route<dynamic>? newRoute,
    _i20.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i20.Route<dynamic>? topRoute,
    _i20.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i20.Route<dynamic>? route,
    _i20.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockUserLocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockUserLocationBloc extends _i1.Mock
    implements _i11.MockUserLocationBloc {
  @override
  _i9.GetLocationUseCase get getLocationUseCase => (super.noSuchMethod(
        Invocation.getter(#getLocationUseCase),
        returnValue: _FakeGetLocationUseCase_7(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
        returnValueForMissingStub: _FakeGetLocationUseCase_7(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
      ) as _i9.GetLocationUseCase);

  @override
  _i9.UserLocationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserLocationState_8(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserLocationState_8(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.UserLocationState);

  @override
  _i12.Stream<_i9.UserLocationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i9.UserLocationState>.empty(),
        returnValueForMissingStub: _i12.Stream<_i9.UserLocationState>.empty(),
      ) as _i12.Stream<_i9.UserLocationState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.UserLocationState fromEither(
          _i22.Either<_i23.Failure, _i9.Location>? eitherFailureOrLocation) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromEither,
          [eitherFailureOrLocation],
        ),
        returnValue: _FakeUserLocationState_8(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
        returnValueForMissingStub: _FakeUserLocationState_8(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
      ) as _i9.UserLocationState);

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void add(_i9.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i9.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.UserLocationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i9.UserLocationEvent>(
    _i14.EventHandler<E, _i9.UserLocationState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i9.UserLocationEvent, _i9.UserLocationState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i9.UserLocationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i14.Change<_i9.UserLocationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockSelectedRestaurantBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockSelectedRestaurantBloc extends _i1.Mock
    implements _i11.MockSelectedRestaurantBloc {
  @override
  _i10.SelectedRestaurantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSelectedRestaurantState_9(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSelectedRestaurantState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i10.SelectedRestaurantState);

  @override
  _i12.Stream<_i10.SelectedRestaurantState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i10.SelectedRestaurantState>.empty(),
        returnValueForMissingStub:
            _i12.Stream<_i10.SelectedRestaurantState>.empty(),
      ) as _i12.Stream<_i10.SelectedRestaurantState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i24.RestaurantSelectedEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i24.RestaurantSelectedEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i10.SelectedRestaurantState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i24.RestaurantSelectedEvent>(
    _i14.EventHandler<E, _i10.SelectedRestaurantState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i14.Transition<_i24.RestaurantSelectedEvent,
                  _i10.SelectedRestaurantState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i24.RestaurantSelectedEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i14.Change<_i10.SelectedRestaurantState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
