// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/homepage/presentation/bloc/popular_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/core/hive/local_user_model.dart' as _i8;
import 'package:rateeat_mobile/src/features/features.dart' as _i2;
import 'package:rateeat_mobile/src/features/homepage/data/datasource/local_homepage_dataprovider.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/popular_items_response.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/user_profile/user_profile.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPopularUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularUseCase extends _i1.Mock implements _i2.GetPopularUseCase {
  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, _i6.PopularItemsResponse>> call(
          _i2.GetPopularItemsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i5.Failure, _i6.PopularItemsResponse>>.value(
                _FakeEither_1<_i5.Failure, _i6.PopularItemsResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i5.Failure, _i6.PopularItemsResponse>>.value(
                _FakeEither_1<_i5.Failure, _i6.PopularItemsResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, _i6.PopularItemsResponse>>);
}

/// A class which mocks [AuthenticationLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalSource extends _i1.Mock
    implements _i2.AuthenticationLocalSource {
  @override
  _i4.Future<void> cacheUserCredential({required _i7.UserModel? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserCredential,
          [],
          {#user: user},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserCredential(
          {required _i8.LocalUserModel? updatedUserInformation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCredential,
          [],
          {#updatedUserInformation: updatedUserInformation},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserCredential() => (super.noSuchMethod(
        Invocation.method(
          #clearUserCredential,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initializeApp() => (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> getAppInitialization() => (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [LocalHomepageDataprovider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalHomepageDataprovider extends _i1.Mock
    implements _i9.LocalHomepageDataprovider {
  @override
  _i4.Future<void> cacheTopRatedItems(List<_i10.Item>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTopRatedItems,
          [items],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.Item>> getTopRatedItems() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedItems,
          [],
        ),
        returnValue: _i4.Future<List<_i10.Item>>.value(<_i10.Item>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.Item>>.value(<_i10.Item>[]),
      ) as _i4.Future<List<_i10.Item>>);

  @override
  _i4.Future<void> clearTopRatedItems() => (super.noSuchMethod(
        Invocation.method(
          #clearTopRatedItems,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
