// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/review/domain/usecases/add_item_review_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/review/data/models/add_item_review_request_model.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/review/data/models/delete_draft_review_request_model.dart'
    as _i11;
import 'package:rateeat_mobile/src/features/review/data/models/delete_item_review_request_model.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/review/data/models/draft_to_review_request_model.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/review/data/models/edit_item_review_request_model.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/review/domain/entities/flag_review.dart'
    as _i12;
import 'package:rateeat_mobile/src/features/review/domain/entities/item_reviews_response.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/review/domain/repositories/item_review_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ItemReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemReviewRepository extends _i1.Mock
    implements _i3.ItemReviewRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          _i6.ItemReviewsResponse>> getItemReviewsByPopularity({
    required dynamic itemId,
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemReviewsByPopularity,
          [],
          {
            #itemId: itemId,
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ItemReviewsResponse>(
          this,
          Invocation.method(
            #getItemReviewsByPopularity,
            [],
            {
              #itemId: itemId,
              #limit: limit,
              #page: page,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ItemReviewsResponse>(
          this,
          Invocation.method(
            #getItemReviewsByPopularity,
            [],
            {
              #itemId: itemId,
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.ItemReviewsResponse>> getItemReviewsByTime({
    required dynamic itemId,
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemReviewsByTime,
          [],
          {
            #itemId: itemId,
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ItemReviewsResponse>(
          this,
          Invocation.method(
            #getItemReviewsByTime,
            [],
            {
              #itemId: itemId,
              #limit: limit,
              #page: page,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ItemReviewsResponse>(
          this,
          Invocation.method(
            #getItemReviewsByTime,
            [],
            {
              #itemId: itemId,
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemReviewsResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> addItemReview({
    required _i7.AddItemReviewRequestModel? addItemReviewRequestModel,
    required bool? isCandidateItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemReview,
          [],
          {
            #addItemReviewRequestModel: addItemReviewRequestModel,
            #isCandidateItem: isCandidateItem,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #addItemReview,
            [],
            {
              #addItemReviewRequestModel: addItemReviewRequestModel,
              #isCandidateItem: isCandidateItem,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #addItemReview,
            [],
            {
              #addItemReviewRequestModel: addItemReviewRequestModel,
              #isCandidateItem: isCandidateItem,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> editItemReview(
          {required _i8.EditItemReviewRequestModel?
              editItemReviewRequestModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editItemReview,
          [],
          {#editItemReviewRequestModel: editItemReviewRequestModel},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #editItemReview,
            [],
            {#editItemReviewRequestModel: editItemReviewRequestModel},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #editItemReview,
            [],
            {#editItemReviewRequestModel: editItemReviewRequestModel},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> deleteItemReview(
          {required _i9.DeleteItemReviewRequestModel?
              deleteItemReviewRequestModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItemReview,
          [],
          {#deleteItemReviewRequestModel: deleteItemReviewRequestModel},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #deleteItemReview,
            [],
            {#deleteItemReviewRequestModel: deleteItemReviewRequestModel},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #deleteItemReview,
            [],
            {#deleteItemReviewRequestModel: deleteItemReviewRequestModel},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> addDraftToReview(
          {required _i10.DraftToReviewRequestModel?
              draftToReviewRequestModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDraftToReview,
          [],
          {#draftToReviewRequestModel: draftToReviewRequestModel},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #addDraftToReview,
            [],
            {#draftToReviewRequestModel: draftToReviewRequestModel},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #addDraftToReview,
            [],
            {#draftToReviewRequestModel: draftToReviewRequestModel},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> deleteDraftItemReview(
          {required _i11.DeleteDraftItemReviewRequestModel?
              deleteDraftItemReviewRequestModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDraftItemReview,
          [],
          {
            #deleteDraftItemReviewRequestModel:
                deleteDraftItemReviewRequestModel
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #deleteDraftItemReview,
            [],
            {
              #deleteDraftItemReviewRequestModel:
                  deleteDraftItemReviewRequestModel
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #deleteDraftItemReview,
            [],
            {
              #deleteDraftItemReviewRequestModel:
                  deleteDraftItemReviewRequestModel
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> flagReview(
          {required _i12.FlagReview? review}) =>
      (super.noSuchMethod(
        Invocation.method(
          #flagReview,
          [],
          {#review: review},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #flagReview,
            [],
            {#review: review},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #flagReview,
            [],
            {#review: review},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
