// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/location_search/domain/usecases/get_location_description_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/location_search/data/models/google_auto_complete_model.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/location_search/data/models/location_coordinate_model.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/location_search/data/models/search_autocomplete_model.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/location_search/domain/repositories/search_location_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchLocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocationRepository extends _i1.Mock
    implements _i3.SearchLocationRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.SearchAutoCompleteModel>>> getLocations(
          {required String? place}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocations,
          [],
          {#place: place},
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i6.SearchAutoCompleteModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SearchAutoCompleteModel>>(
          this,
          Invocation.method(
            #getLocations,
            [],
            {#place: place},
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i6.SearchAutoCompleteModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.SearchAutoCompleteModel>>(
          this,
          Invocation.method(
            #getLocations,
            [],
            {#place: place},
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.SearchAutoCompleteModel>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>> getPlaces(
          {required String? place}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaces,
          [],
          {#place: place},
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>(
          this,
          Invocation.method(
            #getPlaces,
            [],
            {#place: place},
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>(
          this,
          Invocation.method(
            #getPlaces,
            [],
            {#place: place},
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i7.GoogleAutoCompleteModel>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i8.LocationCoordinateModel>> getPlaceCoordinates(
          {required String? placeId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaceCoordinates,
          [],
          {#placeId: placeId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i8.LocationCoordinateModel>>.value(
            _FakeEither_0<_i5.Failure, _i8.LocationCoordinateModel>(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [],
            {#placeId: placeId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i8.LocationCoordinateModel>>.value(
            _FakeEither_0<_i5.Failure, _i8.LocationCoordinateModel>(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [],
            {#placeId: placeId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.LocationCoordinateModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getLocationDescription({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationDescription,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getLocationDescription,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getLocationDescription,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
