// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/discover/presentation/bloc/current_location_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/error/failure.dart' as _i6;
import 'package:rateeat_mobile/src/core/use_case/use_case.dart' as _i8;
import 'package:rateeat_mobile/src/features/discover/data/models/location_model.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/discover/domain/repositories/discover_repo.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/discover/domain/use_cases/get_location_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscoverRepo_0 extends _i1.SmartFake implements _i2.DiscoverRepo {
  _FakeDiscoverRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationUseCase extends _i1.Mock
    implements _i4.GetLocationUseCase {
  @override
  _i2.DiscoverRepo get discoverRepo => (super.noSuchMethod(
        Invocation.getter(#discoverRepo),
        returnValue: _FakeDiscoverRepo_0(
          this,
          Invocation.getter(#discoverRepo),
        ),
        returnValueForMissingStub: _FakeDiscoverRepo_0(
          this,
          Invocation.getter(#discoverRepo),
        ),
      ) as _i2.DiscoverRepo);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocationModel>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.LocationModel>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocationModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.LocationModel>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocationModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocationModel>>);
}
