// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/qr_menu/data/repositories/qr_menu_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/features.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQRMenu_1 extends _i1.SmartFake implements _i3.QRMenu {
  _FakeQRMenu_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQROrder_2 extends _i1.SmartFake implements _i3.QROrder {
  _FakeQROrder_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QRMenuRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRMenuRemoteDatasource extends _i1.Mock
    implements _i3.QRMenuRemoteDatasource {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<_i3.QRMenu> getQRMenu({
    required String? restaurantId,
    required int? page,
    _i3.QRCategory? category,
    bool? isFasting = false,
    required int? limit,
    String? query = r'',
    required String? sortBy,
    required int? minPrice,
    required int? maxPrice,
    required int? minRating,
    required String? sortType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQRMenu,
          [],
          {
            #restaurantId: restaurantId,
            #page: page,
            #category: category,
            #isFasting: isFasting,
            #limit: limit,
            #query: query,
            #sortBy: sortBy,
            #minPrice: minPrice,
            #maxPrice: maxPrice,
            #minRating: minRating,
            #sortType: sortType,
          },
        ),
        returnValue: _i4.Future<_i3.QRMenu>.value(_FakeQRMenu_1(
          this,
          Invocation.method(
            #getQRMenu,
            [],
            {
              #restaurantId: restaurantId,
              #page: page,
              #category: category,
              #isFasting: isFasting,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #minRating: minRating,
              #sortType: sortType,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i3.QRMenu>.value(_FakeQRMenu_1(
          this,
          Invocation.method(
            #getQRMenu,
            [],
            {
              #restaurantId: restaurantId,
              #page: page,
              #category: category,
              #isFasting: isFasting,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #minRating: minRating,
              #sortType: sortType,
            },
          ),
        )),
      ) as _i4.Future<_i3.QRMenu>);

  @override
  _i4.Future<List<_i3.PriceRange>> getNumberOfItemsPerPriceRange({
    required String? restaurantId,
    required bool? isFasting,
    required _i3.QRCategory? category,
    required int? minRating,
    required String? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNumberOfItemsPerPriceRange,
          [],
          {
            #restaurantId: restaurantId,
            #isFasting: isFasting,
            #category: category,
            #minRating: minRating,
            #query: query,
          },
        ),
        returnValue: _i4.Future<List<_i3.PriceRange>>.value(<_i3.PriceRange>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i3.PriceRange>>.value(<_i3.PriceRange>[]),
      ) as _i4.Future<List<_i3.PriceRange>>);

  @override
  _i4.Future<_i3.QROrder> placeQROrder({
    required Map<_i3.QRItem, int>? items,
    required String? restaurantId,
    required String? orderNote,
    required _i3.Location? location,
    required String? orderType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeQROrder,
          [],
          {
            #items: items,
            #restaurantId: restaurantId,
            #orderNote: orderNote,
            #location: location,
            #orderType: orderType,
          },
        ),
        returnValue: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #placeQROrder,
            [],
            {
              #items: items,
              #restaurantId: restaurantId,
              #orderNote: orderNote,
              #location: location,
              #orderType: orderType,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #placeQROrder,
            [],
            {
              #items: items,
              #restaurantId: restaurantId,
              #orderNote: orderNote,
              #location: location,
              #orderType: orderType,
            },
          ),
        )),
      ) as _i4.Future<_i3.QROrder>);

  @override
  _i4.Future<_i3.QROrder> getQROrderDetails({required String? orderId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQROrderDetails,
          [],
          {#orderId: orderId},
        ),
        returnValue: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #getQROrderDetails,
            [],
            {#orderId: orderId},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #getQROrderDetails,
            [],
            {#orderId: orderId},
          ),
        )),
      ) as _i4.Future<_i3.QROrder>);

  @override
  _i4.Future<_i3.QROrder> updateQROrder({
    required String? orderId,
    required Map<_i3.QRItem, int>? items,
    required String? restaurantId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQROrder,
          [],
          {
            #orderId: orderId,
            #items: items,
            #restaurantId: restaurantId,
          },
        ),
        returnValue: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #updateQROrder,
            [],
            {
              #orderId: orderId,
              #items: items,
              #restaurantId: restaurantId,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i3.QROrder>.value(_FakeQROrder_2(
          this,
          Invocation.method(
            #updateQROrder,
            [],
            {
              #orderId: orderId,
              #items: items,
              #restaurantId: restaurantId,
            },
          ),
        )),
      ) as _i4.Future<_i3.QROrder>);
}
