// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/authentication/domain/usecases/signup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/authentication/domain/entities/user_login_response.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/authentication/domain/repositories/authentication_repository.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/user_profile/data/data.dart' as _i8;
import 'package:rateeat_mobile/src/features/user_profile/domain/domain.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i3.AuthenticationRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendEmailOtp(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailOtp,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEmailOtp,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEmailOtp,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>> verifyEmailOtp({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmailOtp,
          [],
          {
            #email: email,
            #code: code,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #verifyEmailOtp,
            [],
            {
              #email: email,
              #code: code,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #verifyEmailOtp,
            [],
            {
              #email: email,
              #code: code,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> resendEmailOtp(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendEmailOtp,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendEmailOtp,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendEmailOtp,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendPhoneOtp(
          {required String? phoneNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPhoneOtp,
          [],
          {#phoneNumber: phoneNumber},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendPhoneOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendPhoneOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendEditPhoneOtp(
          {required String? phoneNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEditPhoneOtp,
          [],
          {#phoneNumber: phoneNumber},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEditPhoneOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEditPhoneOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendEditEmailOtp(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEditEmailOtp,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEditEmailOtp,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendEditEmailOtp,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>> verifyOtp({
    required String? phoneNumber,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #phoneNumber: phoneNumber,
            #code: code,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #phoneNumber: phoneNumber,
              #code: code,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #phoneNumber: phoneNumber,
              #code: code,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> resendOtp(
          {required String? phoneNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOtp,
          [],
          {#phoneNumber: phoneNumber},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendOtp,
            [],
            {#phoneNumber: phoneNumber},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> signUp(
          {required _i8.UserModel? userData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {#userData: userData},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#userData: userData},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
                _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#userData: userData},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>> loginGoogle({
    required String? email,
    required String? accessToken,
    required String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginGoogle,
          [],
          {
            #email: email,
            #accessToken: accessToken,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #loginGoogle,
            [],
            {
              #email: email,
              #accessToken: accessToken,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #loginGoogle,
            [],
            {
              #email: email,
              #accessToken: accessToken,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>> loginFacebook(
          {required String? accessToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginFacebook,
          [],
          {#accessToken: accessToken},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #loginFacebook,
            [],
            {#accessToken: accessToken},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #loginFacebook,
            [],
            {#accessToken: accessToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> signInWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
                _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> logoutWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> signInWithFacebook() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithFacebook,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signInWithFacebook,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
                _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #signInWithFacebook,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> logoutWithFacebook() =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutWithFacebook,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithFacebook,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithFacebook,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          _i6.UserLoginResponse>> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserLoginResponse>(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> signOutWithApple() =>
      (super.noSuchMethod(
        Invocation.method(
          #signOutWithApple,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #signOutWithApple,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #signOutWithApple,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> refreshToken(
          {required String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
                _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);
}
