// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/review/data/repositories/price_update_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:rateeat_mobile/src/features/review/data/datasources/remote_price_review_datasource.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/review/data/models/price_review_request_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PriceReviewDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPriceReviewDataSource extends _i1.Mock
    implements _i2.PriceReviewDataSource {
  @override
  _i3.Future<String> priceReviewRequest(
          {required _i4.PriceReviewRequestModel? priceReviewRequestModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #priceReviewRequest,
          [],
          {#priceReviewRequestModel: priceReviewRequestModel},
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceReviewRequest,
            [],
            {#priceReviewRequestModel: priceReviewRequestModel},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #priceReviewRequest,
            [],
            {#priceReviewRequestModel: priceReviewRequestModel},
          ),
        )),
      ) as _i3.Future<String>);
}
