// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/restaurant_menu/data/repositories/restaurant_menu_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/features/homepage/data/models/models.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/homepage/domain/entities/item.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/restaurant_menu/data/data_sources/restaurant_menu_data_provider.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/restaurant_menu/data/models/restaurant_category.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/restaurant_menu/domain/entities/menu.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMenu_0 extends _i1.SmartFake implements _i2.Menu {
  _FakeMenu_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItem_1 extends _i1.SmartFake implements _i3.Item {
  _FakeItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestaurantMenuDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantMenuDataProvider extends _i1.Mock
    implements _i4.RestaurantMenuDataProvider {
  @override
  _i5.Future<List<_i6.ItemModel>> getRestaurantMenuItems({
    required String? restaurantId,
    required int? limit,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantMenuItems,
          [],
          {
            #restaurantId: restaurantId,
            #limit: limit,
            #page: page,
          },
        ),
        returnValue: _i5.Future<List<_i6.ItemModel>>.value(<_i6.ItemModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.ItemModel>>.value(<_i6.ItemModel>[]),
      ) as _i5.Future<List<_i6.ItemModel>>);

  @override
  _i5.Future<_i2.Menu> getRestaurantMenuCategoryItems({
    required String? restaurantId,
    required String? categoryId,
    required int? page,
    required int? limit,
    required String? query,
    required String? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantMenuCategoryItems,
          [],
          {
            #restaurantId: restaurantId,
            #categoryId: categoryId,
            #page: page,
            #limit: limit,
            #query: query,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i5.Future<_i2.Menu>.value(_FakeMenu_0(
          this,
          Invocation.method(
            #getRestaurantMenuCategoryItems,
            [],
            {
              #restaurantId: restaurantId,
              #categoryId: categoryId,
              #page: page,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Menu>.value(_FakeMenu_0(
          this,
          Invocation.method(
            #getRestaurantMenuCategoryItems,
            [],
            {
              #restaurantId: restaurantId,
              #categoryId: categoryId,
              #page: page,
              #limit: limit,
              #query: query,
              #sortBy: sortBy,
            },
          ),
        )),
      ) as _i5.Future<_i2.Menu>);

  @override
  _i5.Future<_i3.Item> addCandidateItem({
    required String? itemName,
    required String? price,
    required List<_i7.File>? itemImages,
    required String? menuId,
    required String? categoryName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCandidateItem,
          [],
          {
            #itemName: itemName,
            #price: price,
            #itemImages: itemImages,
            #menuId: menuId,
            #categoryName: categoryName,
          },
        ),
        returnValue: _i5.Future<_i3.Item>.value(_FakeItem_1(
          this,
          Invocation.method(
            #addCandidateItem,
            [],
            {
              #itemName: itemName,
              #price: price,
              #itemImages: itemImages,
              #menuId: menuId,
              #categoryName: categoryName,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Item>.value(_FakeItem_1(
          this,
          Invocation.method(
            #addCandidateItem,
            [],
            {
              #itemName: itemName,
              #price: price,
              #itemImages: itemImages,
              #menuId: menuId,
              #categoryName: categoryName,
            },
          ),
        )),
      ) as _i5.Future<_i3.Item>);

  @override
  _i5.Future<List<_i8.RestaurantMenuCategoryModel>> getRestaurantMenuCategories(
          {required String? restaurantId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantMenuCategories,
          [],
          {#restaurantId: restaurantId},
        ),
        returnValue: _i5.Future<List<_i8.RestaurantMenuCategoryModel>>.value(
            <_i8.RestaurantMenuCategoryModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i8.RestaurantMenuCategoryModel>>.value(
                <_i8.RestaurantMenuCategoryModel>[]),
      ) as _i5.Future<List<_i8.RestaurantMenuCategoryModel>>);
}
