// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/search/presentation/widget_test/categories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:dartz/dartz.dart' as _i17;
import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;
import 'package:rateeat_mobile/src/core/core.dart' as _i18;
import 'package:rateeat_mobile/src/features/discover/discover.dart' as _i2;
import 'package:rateeat_mobile/src/features/live_search/presentation/pages/live_search_page.dart'
    as _i23;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/items/get_closest_items_usecase.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/items/get_highest_rated_items_usecase.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/items/get_most_popular_items_use_case.dart'
    as _i4;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/items/get_price_sorted_items_usecase.dart'
    as _i5;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/restaurants/get_closest_restaurants_usecase.dart'
    as _i11;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/restaurants/get_highest_rated_restaurants_usecase.dart'
    as _i9;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/restaurants/get_most_popular_restaurants_usecase.dart'
    as _i8;
import 'package:rateeat_mobile/src/features/search_result/domain/use_cases/restaurants/get_price_sorted_restaurants_usecase.dart'
    as _i10;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/items_filter_search_result/items_filter_results_bloc.dart'
    as _i19;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/items_filter_search_result/items_filter_results_event.dart'
    as _i20;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/items_filter_search_result/items_filter_results_state.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/restaurants_filter_search_result/restaurants_filter_results_bloc.dart'
    as _i21;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/restaurants_filter_search_result/restaurants_filter_results_event.dart'
    as _i22;
import 'package:rateeat_mobile/src/features/search_result/presentation/bloc/restaurants_filter_search_result/restaurants_filter_results_state.dart'
    as _i12;
import 'package:rateeat_mobile/src/features/search_result/presentation/pages/search_result_page.dart'
    as _i13;
import 'package:rateeat_mobile/src/features/search_result/presentation/widgets/categories.dart'
    as _i16;
import 'package:rateeat_mobile/src/features/search_result/presentation/widgets/search_result.dart'
    as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetLocationUseCase_0 extends _i1.SmartFake
    implements _i2.GetLocationUseCase {
  _FakeGetLocationUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserLocationState_1 extends _i1.SmartFake
    implements _i2.UserLocationState {
  _FakeUserLocationState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetHighestRatedItemsUseCase_2 extends _i1.SmartFake
    implements _i3.GetHighestRatedItemsUseCase {
  _FakeGetHighestRatedItemsUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMostPopularItemsUseCase_3 extends _i1.SmartFake
    implements _i4.GetMostPopularItemsUseCase {
  _FakeGetMostPopularItemsUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPriceSortedItemsUseCase_4 extends _i1.SmartFake
    implements _i5.GetPriceSortedItemsUseCase {
  _FakeGetPriceSortedItemsUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetClosestItemsUseCase_5 extends _i1.SmartFake
    implements _i6.GetClosestItemsUseCase {
  _FakeGetClosestItemsUseCase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItemsFilterSearchResultsState_6 extends _i1.SmartFake
    implements _i7.ItemsFilterSearchResultsState {
  _FakeItemsFilterSearchResultsState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMostPopularRestaurantsUseCase_7 extends _i1.SmartFake
    implements _i8.GetMostPopularRestaurantsUseCase {
  _FakeGetMostPopularRestaurantsUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetHighestRatedRestaurantsUseCase_8 extends _i1.SmartFake
    implements _i9.GetHighestRatedRestaurantsUseCase {
  _FakeGetHighestRatedRestaurantsUseCase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPriceSortedRestaurantsUseCase_9 extends _i1.SmartFake
    implements _i10.GetPriceSortedRestaurantsUseCase {
  _FakeGetPriceSortedRestaurantsUseCase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetClosestRestaurantsUseCase_10 extends _i1.SmartFake
    implements _i11.GetClosestRestaurantsUseCase {
  _FakeGetClosestRestaurantsUseCase_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantsFilterSearchResultsState_11 extends _i1.SmartFake
    implements _i12.RestaurantsFilterSearchResultsState {
  _FakeRestaurantsFilterSearchResultsState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoriesToggleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesToggleBloc extends _i1.Mock
    implements _i13.CategoriesToggleBloc {
  @override
  int get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i14.Stream<int> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<int>.empty(),
        returnValueForMissingStub: _i14.Stream<int>.empty(),
      ) as _i14.Stream<int>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  dynamic toggleSwitch(int? index) => super.noSuchMethod(
        Invocation.method(
          #toggleSwitch,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(int? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<int>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [FastingToggleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFastingToggleBloc extends _i1.Mock implements _i16.FastingToggleBloc {
  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i14.Stream<bool> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<bool>.empty(),
        returnValueForMissingStub: _i14.Stream<bool>.empty(),
      ) as _i14.Stream<bool>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void emit(bool? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<bool>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [UserLocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocationBloc extends _i1.Mock implements _i2.UserLocationBloc {
  @override
  _i2.GetLocationUseCase get getLocationUseCase => (super.noSuchMethod(
        Invocation.getter(#getLocationUseCase),
        returnValue: _FakeGetLocationUseCase_0(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
        returnValueForMissingStub: _FakeGetLocationUseCase_0(
          this,
          Invocation.getter(#getLocationUseCase),
        ),
      ) as _i2.GetLocationUseCase);

  @override
  _i2.UserLocationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserLocationState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserLocationState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.UserLocationState);

  @override
  _i14.Stream<_i2.UserLocationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i2.UserLocationState>.empty(),
        returnValueForMissingStub: _i14.Stream<_i2.UserLocationState>.empty(),
      ) as _i14.Stream<_i2.UserLocationState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.UserLocationState fromEither(
          _i17.Either<_i18.Failure, _i2.Location>? eitherFailureOrLocation) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromEither,
          [eitherFailureOrLocation],
        ),
        returnValue: _FakeUserLocationState_1(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
        returnValueForMissingStub: _FakeUserLocationState_1(
          this,
          Invocation.method(
            #fromEither,
            [eitherFailureOrLocation],
          ),
        ),
      ) as _i2.UserLocationState);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void add(_i2.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.UserLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.UserLocationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.UserLocationEvent>(
    _i15.EventHandler<E, _i2.UserLocationState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i2.UserLocationEvent, _i2.UserLocationState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i2.UserLocationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<_i2.UserLocationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ItemsFilterSearchResultsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsFilterSearchResultsBloc extends _i1.Mock
    implements _i19.ItemsFilterSearchResultsBloc {
  @override
  _i3.GetHighestRatedItemsUseCase get getHighestRatedItemsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getHighestRatedItemsUseCase),
        returnValue: _FakeGetHighestRatedItemsUseCase_2(
          this,
          Invocation.getter(#getHighestRatedItemsUseCase),
        ),
        returnValueForMissingStub: _FakeGetHighestRatedItemsUseCase_2(
          this,
          Invocation.getter(#getHighestRatedItemsUseCase),
        ),
      ) as _i3.GetHighestRatedItemsUseCase);

  @override
  _i4.GetMostPopularItemsUseCase get getMostPopularItemsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getMostPopularItemsUseCase),
        returnValue: _FakeGetMostPopularItemsUseCase_3(
          this,
          Invocation.getter(#getMostPopularItemsUseCase),
        ),
        returnValueForMissingStub: _FakeGetMostPopularItemsUseCase_3(
          this,
          Invocation.getter(#getMostPopularItemsUseCase),
        ),
      ) as _i4.GetMostPopularItemsUseCase);

  @override
  _i5.GetPriceSortedItemsUseCase get getPriceSortedItemsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getPriceSortedItemsUseCase),
        returnValue: _FakeGetPriceSortedItemsUseCase_4(
          this,
          Invocation.getter(#getPriceSortedItemsUseCase),
        ),
        returnValueForMissingStub: _FakeGetPriceSortedItemsUseCase_4(
          this,
          Invocation.getter(#getPriceSortedItemsUseCase),
        ),
      ) as _i5.GetPriceSortedItemsUseCase);

  @override
  _i6.GetClosestItemsUseCase get getClosestItemsUseCase => (super.noSuchMethod(
        Invocation.getter(#getClosestItemsUseCase),
        returnValue: _FakeGetClosestItemsUseCase_5(
          this,
          Invocation.getter(#getClosestItemsUseCase),
        ),
        returnValueForMissingStub: _FakeGetClosestItemsUseCase_5(
          this,
          Invocation.getter(#getClosestItemsUseCase),
        ),
      ) as _i6.GetClosestItemsUseCase);

  @override
  _i7.ItemsFilterSearchResultsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeItemsFilterSearchResultsState_6(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeItemsFilterSearchResultsState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.ItemsFilterSearchResultsState);

  @override
  _i14.Stream<_i7.ItemsFilterSearchResultsState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i7.ItemsFilterSearchResultsState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i7.ItemsFilterSearchResultsState>.empty(),
      ) as _i14.Stream<_i7.ItemsFilterSearchResultsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void reset(_i15.Emitter<dynamic>? emit) => super.noSuchMethod(
        Invocation.method(
          #reset,
          [emit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i20.ItemsFilterSearchResultsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i20.ItemsFilterSearchResultsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i7.ItemsFilterSearchResultsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i20.ItemsFilterSearchResultsEvent>(
    _i15.EventHandler<E, _i7.ItemsFilterSearchResultsState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i20.ItemsFilterSearchResultsEvent,
                  _i7.ItemsFilterSearchResultsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i20.ItemsFilterSearchResultsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i15.Change<_i7.ItemsFilterSearchResultsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RestaurantsFilterSearchResultsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantsFilterSearchResultsBloc extends _i1.Mock
    implements _i21.RestaurantsFilterSearchResultsBloc {
  @override
  _i8.GetMostPopularRestaurantsUseCase get getMostPopularRestaurantsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getMostPopularRestaurantsUseCase),
        returnValue: _FakeGetMostPopularRestaurantsUseCase_7(
          this,
          Invocation.getter(#getMostPopularRestaurantsUseCase),
        ),
        returnValueForMissingStub: _FakeGetMostPopularRestaurantsUseCase_7(
          this,
          Invocation.getter(#getMostPopularRestaurantsUseCase),
        ),
      ) as _i8.GetMostPopularRestaurantsUseCase);

  @override
  _i9.GetHighestRatedRestaurantsUseCase get getHighestRatedRestaurantsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getHighestRatedRestaurantsUseCase),
        returnValue: _FakeGetHighestRatedRestaurantsUseCase_8(
          this,
          Invocation.getter(#getHighestRatedRestaurantsUseCase),
        ),
        returnValueForMissingStub: _FakeGetHighestRatedRestaurantsUseCase_8(
          this,
          Invocation.getter(#getHighestRatedRestaurantsUseCase),
        ),
      ) as _i9.GetHighestRatedRestaurantsUseCase);

  @override
  _i10.GetPriceSortedRestaurantsUseCase get getPriceSortedRestaurantsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getPriceSortedRestaurantsUseCase),
        returnValue: _FakeGetPriceSortedRestaurantsUseCase_9(
          this,
          Invocation.getter(#getPriceSortedRestaurantsUseCase),
        ),
        returnValueForMissingStub: _FakeGetPriceSortedRestaurantsUseCase_9(
          this,
          Invocation.getter(#getPriceSortedRestaurantsUseCase),
        ),
      ) as _i10.GetPriceSortedRestaurantsUseCase);

  @override
  _i11.GetClosestRestaurantsUseCase get getClosestRestaurantsUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getClosestRestaurantsUseCase),
        returnValue: _FakeGetClosestRestaurantsUseCase_10(
          this,
          Invocation.getter(#getClosestRestaurantsUseCase),
        ),
        returnValueForMissingStub: _FakeGetClosestRestaurantsUseCase_10(
          this,
          Invocation.getter(#getClosestRestaurantsUseCase),
        ),
      ) as _i11.GetClosestRestaurantsUseCase);

  @override
  _i12.RestaurantsFilterSearchResultsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRestaurantsFilterSearchResultsState_11(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeRestaurantsFilterSearchResultsState_11(
          this,
          Invocation.getter(#state),
        ),
      ) as _i12.RestaurantsFilterSearchResultsState);

  @override
  _i14.Stream<_i12.RestaurantsFilterSearchResultsState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue:
            _i14.Stream<_i12.RestaurantsFilterSearchResultsState>.empty(),
        returnValueForMissingStub:
            _i14.Stream<_i12.RestaurantsFilterSearchResultsState>.empty(),
      ) as _i14.Stream<_i12.RestaurantsFilterSearchResultsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i22.RestaurantsFilterSearchResultsEvent? event) =>
      super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i22.RestaurantsFilterSearchResultsEvent? event) =>
      super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i12.RestaurantsFilterSearchResultsState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i22.RestaurantsFilterSearchResultsEvent>(
    _i15.EventHandler<E, _i12.RestaurantsFilterSearchResultsState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i22.RestaurantsFilterSearchResultsEvent,
                  _i12.RestaurantsFilterSearchResultsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i22.RestaurantsFilterSearchResultsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(
          _i15.Change<_i12.RestaurantsFilterSearchResultsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LiveSearchCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSearchCubit extends _i1.Mock implements _i23.LiveSearchCubit {
  @override
  String get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i24.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i24.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as String);

  @override
  _i14.Stream<String> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<String>.empty(),
        returnValueForMissingStub: _i14.Stream<String>.empty(),
      ) as _i14.Stream<String>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changeQuery(dynamic query) => super.noSuchMethod(
        Invocation.method(
          #changeQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(String? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<String>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [SearchPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPageCubit extends _i1.Mock implements _i25.SearchPageCubit {
  @override
  int get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i14.Stream<int> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<int>.empty(),
        returnValueForMissingStub: _i14.Stream<int>.empty(),
      ) as _i14.Stream<int>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void changePage(dynamic page) => super.noSuchMethod(
        Invocation.method(
          #changePage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(int? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i15.Change<int>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}
