// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/order_history/presentation/bloc/order_detail/order_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i5;
import 'package:rateeat_mobile/src/features/order_history/data/data.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/order_history/domain/domain.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderHistoryRepo_0 extends _i1.SmartFake
    implements _i2.OrderHistoryRepo {
  _FakeOrderHistoryRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetOrderDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrderDetailUseCase extends _i1.Mock
    implements _i2.GetOrderDetailUseCase {
  @override
  _i2.OrderHistoryRepo get orderHistoryRepo => (super.noSuchMethod(
        Invocation.getter(#orderHistoryRepo),
        returnValue: _FakeOrderHistoryRepo_0(
          this,
          Invocation.getter(#orderHistoryRepo),
        ),
        returnValueForMissingStub: _FakeOrderHistoryRepo_0(
          this,
          Invocation.getter(#orderHistoryRepo),
        ),
      ) as _i2.OrderHistoryRepo);

  @override
  _i4.Future<_i3.Either<_i5.Failure, _i6.OrderDetailModel>> call(
          _i2.GetOrderDetailParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i3.Either<_i5.Failure, _i6.OrderDetailModel>>.value(
                _FakeEither_1<_i5.Failure, _i6.OrderDetailModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Either<_i5.Failure, _i6.OrderDetailModel>>.value(
                _FakeEither_1<_i5.Failure, _i6.OrderDetailModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, _i6.OrderDetailModel>>);
}
