// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/leaderboard/presentation/bloc/weekly_leader_bioc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rateeat_mobile/src/core/core.dart' as _i6;
import 'package:rateeat_mobile/src/features/leaderboard/domain/entities/weekly_leader_board_responses.dart'
    as _i7;
import 'package:rateeat_mobile/src/features/leaderboard/domain/repositories/leader_board_repository.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/leaderboard/domain/usecases/weekly_leader_board_usecase.dart'
    as _i8;

import 'weekly_leader_bioc_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLeaderRepository_0 extends _i1.SmartFake
    implements _i2.LeaderRepository {
  _FakeLeaderRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockGetWeeklyLeaderBoardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockGetWeeklyLeaderBoardUseCase extends _i1.Mock
    implements _i4.MockGetWeeklyLeaderBoardUseCase {
  MockMockGetWeeklyLeaderBoardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LeaderRepository get leaderRepository => (super.noSuchMethod(
        Invocation.getter(#leaderRepository),
        returnValue: _FakeLeaderRepository_0(
          this,
          Invocation.getter(#leaderRepository),
        ),
      ) as _i2.LeaderRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WeeklyLeaderBoardResponses>> call(
          _i8.GetWeeklyLeaderBoardParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i7.WeeklyLeaderBoardResponses>>.value(
            _FakeEither_1<_i6.Failure, _i7.WeeklyLeaderBoardResponses>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.WeeklyLeaderBoardResponses>>);
}
