// Mocks generated by Mockito 5.4.4 from annotations
// in rateeat_mobile/test/features/location_search/data/repositories/search_location_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:rateeat_mobile/src/features/location_search/data/datasources/remote_source.dart'
    as _i3;
import 'package:rateeat_mobile/src/features/location_search/data/models/google_auto_complete_model.dart'
    as _i6;
import 'package:rateeat_mobile/src/features/location_search/data/models/location_coordinate_model.dart'
    as _i2;
import 'package:rateeat_mobile/src/features/location_search/data/models/search_autocomplete_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocationCoordinateModel_0 extends _i1.SmartFake
    implements _i2.LocationCoordinateModel {
  _FakeLocationCoordinateModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchLocationRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocationRemoteSource extends _i1.Mock
    implements _i3.SearchLocationRemoteSource {
  @override
  _i4.Future<List<_i5.SearchAutoCompleteModel>> getLocations(
          {required String? place}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocations,
          [],
          {#place: place},
        ),
        returnValue: _i4.Future<List<_i5.SearchAutoCompleteModel>>.value(
            <_i5.SearchAutoCompleteModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.SearchAutoCompleteModel>>.value(
                <_i5.SearchAutoCompleteModel>[]),
      ) as _i4.Future<List<_i5.SearchAutoCompleteModel>>);

  @override
  _i4.Future<List<_i6.GoogleAutoCompleteModel>> getPlaces(
          {required String? place}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaces,
          [],
          {#place: place},
        ),
        returnValue: _i4.Future<List<_i6.GoogleAutoCompleteModel>>.value(
            <_i6.GoogleAutoCompleteModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.GoogleAutoCompleteModel>>.value(
                <_i6.GoogleAutoCompleteModel>[]),
      ) as _i4.Future<List<_i6.GoogleAutoCompleteModel>>);

  @override
  _i4.Future<_i2.LocationCoordinateModel> getPlaceCoordinates(
          {required String? placeId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaceCoordinates,
          [],
          {#placeId: placeId},
        ),
        returnValue: _i4.Future<_i2.LocationCoordinateModel>.value(
            _FakeLocationCoordinateModel_0(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [],
            {#placeId: placeId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.LocationCoordinateModel>.value(
                _FakeLocationCoordinateModel_0(
          this,
          Invocation.method(
            #getPlaceCoordinates,
            [],
            {#placeId: placeId},
          ),
        )),
      ) as _i4.Future<_i2.LocationCoordinateModel>);

  @override
  _i4.Future<String> getLocationDescription({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationDescription,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationDescription,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationDescription,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<String>);
}
